---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= NetApp 解決方案搭配受管理的 Red Hat OpenShift Container 平台工作負載
:allow-uri-read: 




== NetApp 解決方案搭配受管理的 Red Hat OpenShift Container 平台工作負載

[role="lead"]
客戶可能是「天生於雲端」、或是準備好將某些特定工作負載或所有工作負載從資料中心移至雲端時、處於現代化過程的某個階段。他們可以選擇在雲端使用由供應商管理的 OpenShift 容器和由供應商管理的 NetApp 儲存設備來執行工作負載。他們應該規劃並部署雲端中的託管 Red Hat OpenShift 容器叢集、以便為其容器工作負載提供成功的正式作業環境。NetApp 在所有三大公有雲中、均為託管 Red Hat 解決方案提供完全託管的儲存產品。

* Amazon FSX for NetApp ONTAP （ FSX ONTAP ） *

FSX ONTAP 為 AWS 中的容器部署提供資料保護、可靠性和靈活度。Trident 是動態儲存資源配置程式、可為客戶的有狀態應用程式使用持續的 FSX ONTAP 儲存設備。

由於 ROSA 可在 HA 模式中部署、控制平面節點分散於多個可用性區域、因此也可透過 Multi-AZ 選項來配置 FSX ONTAP 、以提供高可用度並防範 AZ 故障。

* Google Cloud NetApp Volumes *

Red Hat OpenShift Dedicated 是完全託管的應用程式平台、可讓您在混合雲中快速建置、部署及擴充應用程式。Google Cloud NetApp Volumes 提供永續性的 Volume 、將 ONTAP 的完整企業資料管理功能套件帶入 Google Cloud 中的 OpenShift 部署。
