---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Trident Protect, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= 適用於 Red Hat OpenShift Container 工作負載的 NetApp 混合式多雲端解決方案的價值主張
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
大多數客戶不只是在沒有任何現有基礎架構的情況下、就開始建置 Kubernetes 型環境。或許他們是一家傳統的 IT 商店、在虛擬機器上執行大部分的企業應用程式（例如大型 VMware 環境）。然後他們開始建置小型的容器型環境、以滿足其現代化應用程式開發團隊的需求。這些計畫通常從小規模開始、隨著團隊學習這些新技術和技能、開始變得更普及、並開始認識採用這些技術和技能的許多好處。客戶的好消息是 NetApp 可以滿足這兩種環境的需求。這套適用於混合式多雲端與 Red Hat OpenShift 的解決方案、可讓 NetApp 客戶採用現代化的雲端技術與服務、而無需徹底檢修整個基礎架構與組織。無論客戶的應用程式和資料是在內部部署、雲端、在虛擬機器上執行、或是在容器上執行、 NetApp 都能提供一致的資料管理、保護、安全性和可攜性。有了這些新解決方案、 NetApp 在內部部署資料中心環境中所提供的價值數十年來、將可在整個企業資料領域中提供、而無需投入大量資金來重新調整、取得新技能或建立新團隊。無論客戶的雲端旅程處於何種階段、 NetApp 都能協助客戶解決這些業務挑戰。

NetApp 混合式多雲端搭配 Red Hat Openshift ：

* 為客戶提供經過驗證的設計和實務做法、以示範客戶在使用 Red Hat OpenShift 搭配 NetApp 型儲存解決方案時、如何管理、保護、保護及移轉資料和應用程式的最佳方法。
* 針對在 VMware 環境、裸機基礎架構或兩者的組合中、搭配 NetApp 儲存設備執行 Red Hat OpenShift 的客戶、提供最佳實務做法。
* 針對內部部署和雲端環境、以及兩者都使用的混合式環境、示範策略和選項。

