---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: 本節涵蓋用於 dremio 認證的硬體與軟體。此資訊適用於搭配 NetApp 儲存設備的 dremio 部署。 
---
= 解決方案總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
混合式冰山 Lakehouse 解決方案提供獨特的優勢、可因應資料湖客戶所面臨的客戶挑戰。藉由運用 Dremio Unified Lakehouse 平台和 NetApp ONTAP 、 StorageGRID 和 NetApp 雲端解決方案、公司可以為其業務營運增加重大價值。此解決方案不僅提供多個資料來源的存取、包括 NetApp 來源、也能提升整體分析效能、協助公司推動業務洞見、進而推動業務成長。



== NetApp總覽

* NetApp 的產品（例如 ONTAP 和 StorageGRID ）可分離儲存和運算、根據特定需求提供最佳的資源使用率。這種靈活度可讓客戶使用 NetApp 儲存解決方案來擴充儲存設備
* 藉由運用 NetApp 的儲存控制器、客戶可以使用 NFS 和 S3 傳輸協定、將資料有效地提供給向量資料庫。這些通訊協定可協助客戶儲存資料並管理向量資料庫索引、不需要透過檔案和物件方法存取多個資料複本。
* NetApp ONTAP 在 AWS 、 Azure 和 Google Cloud 等頂尖雲端服務供應商之間、提供 NAS 和物件儲存的原生支援。這種廣泛的相容性可確保無縫整合、實現客戶資料的行動力、全球存取能力、災難恢復、動態擴充性和高效能。




=== StorageGRID

我們領先業界的物件儲存 StorageGRID 提供強大的原則引擎、可自動放置資料、提供靈活的部署選項、以及無與倫比的耐用性與分層銷毀編碼。它擁有可擴充的架構、可在單一命名空間中支援數十億個物件和 PB 的資料。此解決方案可實現混合雲整合、讓資料分層化至主要雲端平台。在 2019 年 IDC Marketscape 全球物件型廠商評估中、 IT 獲公認為領導者。

此外、 StorageGRID 還具備軟體定義的物件儲存、地理區備援和多站台功能、可協助您大規模管理非結構化資料。它整合了原則型資訊生命週期管理、並提供鏡射和搜尋等雲端整合功能。本公司擁有多項認證、包括通用標準、 NF203 數位安全元件、 ISO/IEC 25051 、 KPMG 、以及 Cohasset 法規遵循評估。

總而言之、 NetApp StorageGRID 提供強大的功能、擴充性、混合雲整合、以及法規遵循認證、可有效大規模管理非結構化資料。



=== NetApp ONTAP

NetApp ONTAP 是一款功能強大的儲存解決方案、提供各種企業功能。其中包含 Snapshot 、可提供應用程式一致且防竄改的即時備份。SnapRestore 可隨需即時還原備份、而 SnapMirror 則提供整合式遠端備份與災難恢復功能。此解決方案也整合了自動勒索軟體保護（ ARP ）、以多重系統管理員驗證、 FIPS 認證的靜態資料加密、傳輸中資料加密、多因素驗證（ MFA ）、以及角色型存取控制（ RBAC ）等功能、確保資料安全。全面的記錄、稽核、內建與外部金鑰管理、安全清除、以及安全管理多個租戶、進一步強化資料安全性與法規遵循。

NetApp ONTAP 也採用 SnapLock 、以低總持有成本提供符合法規要求的資料保留功能、提供高層級的完整性、效能和保留。它與 NetApp ONTAP ® 9 完全整合、可防範惡意行為、惡意管理員和勒索軟體。

此解決方案包含 NSE/NVE 加密、可用於執行中和資料靜止加密、多因素管理存取、以及多重管理驗證。Active IQ 提供 AI 導向的預測分析和修正行動、而 QoS 則可確保服務工作負載的品質控制。透過 SysMgr/GUI/CLI/API 、管理與自動化整合是直覺式的。FabricPool 可實現自動資料分層、而此解決方案可透過內嵌資料壓縮、重複資料刪除和壓縮等方式、提供效率。NetApp 保證客戶能免費達成工作負載效率目標。

NetApp ONTAP 支援各種通訊協定、包括 NVMe / FC 、 FC 、 NVMe / TCP 、 iSCSI 、 NFS 、 SMB 和 S3 、使其成為統一化儲存解決方案。總的來說、 NetApp ONTAP 提供廣泛的企業功能、強大的安全性、法規遵循、效率和多用途性、以滿足各種儲存需求。



== Dremio 總覽

Dremio 是 Unified Lakehouse 平台、用於自助分析和 AI 。Dremio Unified Analytics Platform 以舊有資料倉儲解決方案的一小部分成本、提供 Lakehouse 的靈活度、擴充性和效能、讓使用者更接近資料。Dremio 啟用「左移」分析功能、可消除複雜且昂貴的資料整合和 ETL 、提供無縫的企業級分析、無需資料移動。Dremio 也具備下列特色：

* 透過通用語義層和緊密整合、高效能的 SQL 查詢引擎、提供易於使用的自助服務分析功能、讓您更輕鬆地在雲端和內部部署中連線、管理及分析所有資料。
* Dremio 的 Apache iceberg- 原生湖屋管理功能可簡化資料探索、並自動化資料最佳化、以 Git 為靈感的資料版本管理功能提供高效能分析。
* 在開放原始碼和開放式標準的基礎上、 Dremio 讓公司能夠避免束縛、並保持創新的定位。企業公司相信 Dremio 是最容易使用的 Lakehouse 平台、能在所有工作負載中提供最佳的價格效能。




== Dremio 和 NetApp Hybrid 冰山 Lakehouse 解決方案能為客戶帶來什麼價值？

* * 改善資料管理與存取能力 * ： Dremio 以其資料湖平台聞名、可讓組織以高速從資料湖直接查詢資料。另一方面、 NetApp 則是雲端資料服務與資料儲存解決方案的領導供應商。這項聯合方案可為客戶提供全方位的解決方案、讓客戶以高效率且有效率的方式儲存、管理、存取及分析企業資料。
* * 效能最佳化 * ：憑藉 NetApp 在資料儲存和 Dremio 在 Data Processing 與資料最佳化方面的專業知識、這項合作夥伴關係提供了一套解決方案、可改善資料作業效能、縮短延遲時間、並加快業務洞察速度。Dremio 甚至為 NetApp 本身的內部 IT 分析基礎架構提供效能優勢。
* * 擴充性 * ： Dremio 和 NetApp 都提供專為擴充而設計的解決方案。這套聯合解決方案為客戶提供可高度擴充的資料儲存、資料管理和分析環境。在混合式冰山 Lakehouse 環境中、與 NetApp StorageGRID 搭配使用的 Dremio SQL 查詢引擎可提供無與倫比的擴充性、並行性和查詢效能、能夠處理任何企業的分析需求。
* * 資料安全與治理 * ：兩家公司都非常重視資料安全與治理。它們共同提供強大的安全性和資料治理功能、確保資料受到保護、並符合資料治理需求。功能包括角色型和精細存取控制、全方位稽核、端點對端點資料系列、統一化身分識別管理、以及具廣泛法規遵循與安全架構的 SSO 、確保公司的分析資料環境安全無虞且受到妥善管理。
* * 成本效益 * ：透過將 Dremio 的資料湖引擎與 NetApp 的儲存解決方案整合、客戶可以降低與資料管理和資料移動相關的成本。組織也能從舊版資料湖環境移轉到由 NetApp 和 Dremio 組成的更現代化的湖屋解決方案。這款混合式冰山 Lakehouse 解決方案提供高速查詢效能、以及領先市場的查詢並行處理功能、可降低 TCO 並縮短企業洞悉時間。

