---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: 本解決方案提供在 NetApp 儲存設備上部署 Hyper-V 所需的步驟 
---
= 在 NetApp 儲存設備上部署 Microsoft Hyper-V
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Windows Server 平台使用 Hyper-V 角色來提供虛擬化技術。Hyper-V 是 Windows Server 提供的眾多選用角色之一。



== 總覽

Hyper-V 角色可讓我們使用 Windows Server 內建的虛擬化技術、建立及管理虛擬化運算環境。Hyper-V 技術會虛擬化硬體、提供一個環境、讓您可以在一部實體電腦上同時執行多個作業系統。Hyper-V 可讓您建立及管理虛擬機器及其資源。每個虛擬機器都是獨立的虛擬化電腦系統、可以執行自己的作業系統。Hyper-V 提供基礎架構來虛擬化應用程式與工作負載、以支援各種業務目標、以提高效率並降低成本、這是 VMware ® vSphere 的最佳替代方案、尤其是在企業組織在目前的市場環境中、正在尋求共存的多個 Hypervisor 時。



== 目標對象

本文件說明 Hyper-V 叢集組態與 NetApp ONTAP 系統的架構與部署程序。本文件的目標對象包括銷售工程師、現場顧問、專業服務、 IT 經理、合作夥伴工程師、 以及想要將 Hyper-V 部署為主要或替代 Hypervisor 的客戶。



== 架構

本文檔中介紹的架構具體包括 Microsoft ® Windows Server ® 2022 和 Hyper-V ® 虛擬化。NetApp 強烈建議您在每次部署中都使用虛擬化軟體和基礎架構管理軟體。此組態使用每個元件的最佳實務做法、以實現可靠的企業級基礎架構。



== 使用案例摘要

本文件說明在使用 NetApp All Flash FAS 和 ASA 陣列機型的 Microsoft Windows Server 2022 上、設定 Hyper-V 叢集以最佳方式執行工作負載的部署程序和最佳實務做法。伺服器作業系統 / Hypervisor 是 Microsoft Windows Server 2022 。本指南涵蓋透過儲存區域網路（ SAN ）和網路附加儲存（ NAS ）傳輸協定來處理資料的 NetApp 儲存系統。
