---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp解決方案文件
    url: "/index.html"
  - section: ai
  - section: containers
  - section: data-access
  - title: 企業應用程式
    entries:
    - title: SAP SAP HANA
      url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - section: databases
  - section: data-analytics
  - section: ehc
  - section: rhhc
  - section: virtualization
  - section: automation
  - title: 解決方案FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: 老NetApp HCI 舊的解決方案
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: 變更記錄
    url: "/change-log-display.html"
  - title: 關於NetApp解決方案
    url: "/about.html"
  - title: 法律聲明
    url: "/legal-notices.html"
