---
settings:
  name: NetApp Solutions
  harmony_integration: maestro
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp解決方案文件
    url: index.html
  - section: ai
  - section: data-analytics
  - section: cloud
  - section: virtualization
  - section: containers
  - section: databases
  - title: SAP SAP HANA
    url: https://docs.netapp.com/us-en/netapp-solutions-sap/
  - title: 解決方案FlexPod
    url: https://docs.netapp.com/us-en/flexpod/
  - title: 變更記錄
    url: change-log-display.html
  - title: 關於NetApp解決方案
    url: about.html
  - title: 法律聲明
    url: "/legal-notices.html"
