---
sidebar: sidebar 
permalink: videos.html 
summary: 一系列影片和示範、討論NetApp許多解決方案的功能 
keywords: netapp, solutions, videos, demos 
---
= NetApp解決方案：影片與示範
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
影片與示範總覽、重點介紹許多NetApp解決方案的特定功能。

.人工智慧（AI）與現代化資料分析
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["NetApp AI解決方案"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps"^]


====
.企業應用程式與資料庫
[#db%collapsible]
====
[Underlines]#*開放原始碼資料庫的影片*#

.PostgreSQL自動化部署、HA/DR複寫設定、容錯移轉、重新同步
video::e479b91f-eacd-46bf-bfa1-b01200f0015[panopto,width=360]
[Underlin]#*影片：AWS和FS6*#採用混合雲進行Oracle現代化

.第1部分：使用案例和解決方案架構
video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto,width=360]
.第2a部分：使用自動化的pdb重新配置功能、以最大可用度從內部部署移轉至AWS的資料庫
video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto,width=360]
.第2b部分：透過SnapMirror使用BlueXP主控台、將資料庫從內部部署移轉至AWS
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto,width=360]
.第3部分：自動化資料庫HA/DR複寫設定、容錯移轉、重新同步
video::5fd03759-a691-4007-9748-b01200f3b79c[panopto,width=360]
.第4a部分：資料庫複製、以SnapCenter 從複製的待機複本中使用EZUI進行開發/測試
video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto,width=360]
.第4b部分：資料庫備份、還原、複製使用SnapCenter 者介面
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto,width=360]
.第4c部分：資料庫備份、利用BlueXP SaaS應用程式備份與還原
video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto,width=360]
[Underlines]#* SQL Server資料庫的影片*

.在AWS EC2上使用Amazon FSX for NetApp ONTAP ®部署SQL Server
video::27f28284-433d-4273-8748-b01200fb3cd7[panopto,width=360]
.使用儲存快照的Oracle多租戶可插拔資料庫複製
video::krzMWjrrMb0[youtube,width=360]
.利用FlexPod Ansible在支援的基礎上自動部署Oracle 19c RAC
video::VcQMJIRzhoY[youtube,width=360]
*案例研究*

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["SAP on Azure NetApp Files"^]


====
.混合式多雲端（HMC）
[#hmc%collapsible]
====
[Underlines]#*適用於AWS/VMC*#的影片

.Windows Guest連線儲存設備搭配ONTAP 使用iSCSI的FSX功能
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Linux Guest連線儲存設備搭配ONTAP 使用NFS的FSX功能
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
. 採用Amazon FSX for NetApp ONTAP 的VMware Cloud on AWS TCO節約效益
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud on AWS補充資料存放區搭配Amazon FSX for NetApp ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.適用於VMC的VMware HCX部署與組態設定
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMware HCX for VMC 和 FSxN 的 VMotion 移轉示範
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMware HCX for VMC和FSxN的冷移轉示範
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
[Underlines]#* Azure / AVS*#影片

.Azure VMware解決方案補充資料存放區總覽Azure NetApp Files （含）
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
. Azure VMware解決方案DR Cloud Volumes ONTAP 搭配VMware功能、包括功能不完整、SnapCenter 功能完整
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX針對AVS和ANF進行冷移轉示範
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX針對AVS和ANF的VMotion示範
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.VMware HCX針對AVS和ANF的大量移轉示範
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.混合式 MultiCloud 搭配 Red Hat OpenShift
[#rhhc%collapsible]
====
.ROSA DR 使用 Astra Control Service
video::01dd455e-7f5a-421c-b501-b01200fa91fd[panopto,width=360]
.將 FSxN 與 Astra Trident 整合
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.透過 FSxN 在 ROSA 上容錯移轉和容錯回復應用程式
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]
[ 底線 ]#*DR 使用 Astra Control Center*#

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["在 NetAppTV 上觀看"]

.在 Google Cloud Platform 上安裝 OpenShift 叢集
video::4efc68f1-d37f-4cdd-874a-b09700e71da9[panopto,width=360]
.將 OpenShift 叢集匯入 Astra Control Center
video::57b63822-6bf0-4d7b-b844-b09700eac6ac[panopto,width=360]
.Astra Control Center 提供資料保護功能
video::0cec0c90-4c6f-4018-9e4f-b09700eefb3a[panopto,width=360]
====
.虛擬化
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["VMware影片集"]


====
.Container / Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["NetApp與Google Anthos影片"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["NetApp與VMware Tanzu影片"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["NetApp DevOps影片"]
* link:containers/rh-os-n_videos_and_demos.html["NetApp與Red Hat OpenShift影片"]


====
.解決方案自動化
[#automation%collapsible]
====
.利用FlexPod Ansible在支援的基礎上自動部署Oracle 19c RAC
video::VcQMJIRzhoY[youtube,width=360]
====