---
sidebar: sidebar 
permalink: ehc/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 適用於AWS VMC的NetApp功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
深入瞭解NetApp為AWS VMware Cloud（VMC）帶來的功能：從NetApp做為來賓連線儲存設備或補充NFS資料存放區、移轉工作流程、延伸/突增至雲端、備份/還原及災難恢復。

從下列選項中選取、跳至所需內容的區段：

* link:#config["在AWS中設定VMC"]
* link:#datastore["適用於VMC的NetApp儲存選項"]
* link:#solutions["NetApp / VMware雲端解決方案"]




== 在AWS中設定VMC

如同內部部署、規劃雲端型虛擬化環境對於成功建立虛擬機器和移轉的正式作業就緒環境來說、是非常重要的。

本節說明如何在AWS SDDC上設定及管理VMware Cloud、並搭配可用的選項來連接NetApp儲存設備。


NOTE: 客體內儲存設備是唯一支援的將Cloud Volumes ONTAP 功能連接到AWS VMC的方法。

設定程序可分為下列步驟：

* 部署及設定適用於AWS的VMware Cloud
* 將VMware Cloud連接至FSX ONTAP VMware


檢視詳細資訊 link:aws-setup.html["VMC的組態步驟"]。



== 適用於VMC的NetApp儲存選項

NetApp儲存設備可在AWS VMC中以多種方式使用、例如猜測連接的或補充的NFS資料存放區。

請造訪 link:ehc-support-configs.html["支援的NetApp儲存選項"] 以取得更多資訊。

AWS支援下列組態的NetApp儲存設備：

* FSX ONTAP 支援以客為本的連線儲存設備
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* FSX ONTAP 不只是NFS的補充資料存放區


檢視詳細資訊 link:aws-guest.html["VMC的來賓連線儲存選項"]。檢視詳細資訊 link:aws-native-nfs-datastore-option.html["VMC的補充NFS資料存放區選項"]。



== 解決方案使用案例

有了NetApp和VMware雲端解決方案、許多使用案例都很容易部署在AWS VMC中。每個VMware定義的雲端領域都定義了使用案例：

* 保護（包括災難恢復和備份/還原）
* 延伸
* 移轉


link:aws-solutions.html["瀏覽NetApp的AWS VMC解決方案"]
