---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= NetApp混合式多雲端與VMware的使用案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在規劃混合雲或雲端優先部署時、對IT組織而言重要的使用案例總覽。



== 熱門使用案例

使用案例包括：

* 災難恢復、
* 在資料中心維護期間代管工作負載*快速爆發、除了本機資料中心的資源配置之外、還需要額外的資源、
* VMware站台擴充、
* 快速移轉至雲端、
* 開發/測試、及
* 運用雲端輔助技術來現代化應用程式。


在本文件中、我們將使用VMware使用案例來詳細說明雲端工作負載參考資料。這些使用案例包括：

* 保護（包括災難恢復和備份/還原）
* 移轉
* 延伸




=== IT發展歷程中

大多數組織都在轉型與現代化的過程中。在這個流程中、公司正嘗試使用現有的VMware投資、同時善用雲端效益、並探索各種方法、使移轉程序盡可能順暢無礙。這種方法會讓他們的現代化工作變得非常簡單、因為資料已經在雲端中。

此案例最簡單的答案是每個超大規模擴充系統中的VMware產品。如同NetApp®Cloud Volumes、VMware提供一種將內部部署VMware環境移轉或延伸至任何雲端的方法、讓您保留現有的內部部署資產、技能和工具、同時在雲端原生執行工作負載。如此可降低風險、因為不會發生服務中斷或需要變更IP、讓IT團隊能夠使用現有的技能和工具、以內部部署的方式操作。如此一來、雲端移轉速度就會加快、並能更順暢地移轉至混合式多雲端架構。



=== 瞭解補充NFS儲存選項的重要性

雖然VMware在任何雲端上都能為每位客戶提供獨特的混合式功能、但有限的補充NFS儲存選項限制了它對於儲存繁重工作負載的組織的效用。由於儲存設備直接與主機相連、因此擴充儲存設備的唯一方法是新增更多主機、而且儲存密集型工作負載的成本會增加35%至40%以上。這些工作負載只需要額外的儲存容量、而非額外的馬力。但這表示需要支付額外的主機費用。

讓我們來思考以下案例：

客戶只需要五部主機來處理CPU和記憶體、但需要大量的儲存需求、而且需要12部主機來滿足儲存需求。這項需求最終會在只需要增加儲存容量的情況下、購買額外的馬力、進而大幅提高財務規模。

當您規劃雲端採用和移轉時、務必評估最佳方法、並採取最簡單的方法來減少總投資。任何應用程式移轉最常見且最簡單的方法、就是在沒有虛擬機器（VM）或資料轉換的情況下、重新裝載（也稱為移轉）。使用NetApp Cloud Volumes搭配VMware軟體定義資料中心（SDDC）、同時輔助vSAN、可提供輕鬆的移轉選項。
