---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= 適用於公有雲供應商的NetApp儲存選項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在三大大型超大規模擴充系統中探索NetApp儲存設備的選項。

[role="tabbed-block"]
====
.AWS / VMC
--
AWS支援下列組態的NetApp儲存設備：

* FSX ONTAP 支援以客為本的連線儲存設備
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* FSX ONTAP 不只是NFS的補充資料存放區


檢視詳細資訊 link:aws-guest.html["VMC的來賓連線儲存選項"]。檢視詳細資訊 link:aws-native-nfs-datastore-option.html["VMC的補充NFS資料存放區選項"]。

--
.Azure / AVS
--
Azure以下列組態支援NetApp儲存設備：

* 以客體連線儲存設備的形式提供Azure NetApp Files
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* 作爲NFS補充資料存放區的能力（ANF Azure NetApp Files ）


檢視詳細資訊 link:azure-guest.html["AVS的來賓連線儲存選項"]。檢視詳細資訊 link:azure-native-nfs-datastore-option.html["AVS的補充NFS資料存放區選項"]。

--
.GCP / GCV
--
Google Cloud支援下列組態的NetApp儲存設備：

* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* Google Cloud NetApp Volumes （ NetApp Volumes ）做為來賓連線儲存設備
* Google Cloud NetApp Volumes （ NetApp Volumes ）做為補充 NFS 資料存放區


查看詳細信息link:gcp-guest.html["GCVE的來賓連線儲存選項"]。查看詳細信息link:gcp-ncvs-datastore.html["GCVE的補充NFS資料存放區選項"]。

深入瞭解link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp Volumes 資料存放區支援 Google Cloud VMware Engine （ NetApp 部落格）"^]或link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["如何使用 Google Cloud NetApp Volumes 做為 Google Cloud VMware Engine 的資料存放區（ Google 部落格）"^]

--
====