---
sidebar: sidebar 
permalink: ehc/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 適用於Google Cloud Platform GCVE的NetApp功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
深入瞭解 NetApp 提供給 Google Cloud Platform （ GCP ） Google Cloud VMware Engine （ GCVE ）的功能：從 NetApp 作為來賓連線儲存設備、或是輔助 NFS 資料存放區、移轉工作流程、擴充 / 突增至雲端、備份 / 還原及災難恢復。

從下列選項中選取、跳至所需內容的區段：

* link:#config["在GCP中設定GCVE"]
* link:#datastore["適用於GCVE的NetApp儲存選項"]
* link:#solutions["NetApp / VMware雲端解決方案"]




== 在GCP中設定GCVE

如同內部部署、規劃雲端型虛擬化環境對於成功建立虛擬機器和移轉的正式作業就緒環境來說、是非常重要的。

本節說明如何設定及管理GCVE,並搭配可用的選項來連接NetApp儲存設備。


NOTE: 客體內儲存設備是唯一支援的方法、可將Cloud Volumes ONTAP 「效益」和「雲端Volume服務」連線至GCVE.

設定程序可分為下列步驟：

* 部署及設定GCVE
* 啟用對GCVE的私有存取


檢視詳細資訊 link:gcp-setup.html["GCVE.的組態步驟"]。



== 適用於GCVE的NetApp儲存選項

NetApp儲存設備可在GCP GCVG內以多種方式使用、無論是作為猜測連接或作為補充NFS資料存放區。

請造訪 link:ehc-support-configs.html["支援的NetApp儲存選項"] 以取得更多資訊。

Google Cloud支援下列組態的NetApp儲存設備：

* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* 以客體連線儲存設備的形式提供資訊（CVS）Cloud Volumes Service
* 作爲NFS補充資料存放區的CVS Cloud Volumes Service


檢視詳細資訊 link:gcp-guest.html["GCVE的來賓連線儲存選項"]。

深入瞭解 link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["NetApp Cloud Volumes Service 支援Google Cloud VMware Engine的資料儲存區（NetApp部落格）"^] 或 link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["如何使用NetApp CVS做為Google Cloud VMware Engine的資料存放區（Google部落格）"^]



== 解決方案使用案例

有了NetApp和VMware雲端解決方案、在Azure AVS中部署的許多使用案例都很簡單。系統會針對VMware定義的每個雲端領域定義SE案例：

* 保護（包括災難恢復和備份/還原）
* 延伸
* 移轉


link:gcp-solutions.html["瀏覽適用於Google Cloud GCVE的NetApp解決方案"]
