---
sidebar: sidebar 
permalink: containers/anthos-with-netapp/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: NetApp提供多種產品、協助客戶在Anthos等容器型環境中協調及管理持續資料。 
---
= NetApp儲存整合概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== Anthos Ready儲存合作夥伴方案。

Google Cloud會定期透過Anthos Ready儲存合作夥伴方案、要求更新合作夥伴儲存整合與新版Anthos的驗證。您可以找到目前已驗證的儲存解決方案、csi驅動程式、可用功能及所支援的Anthos版本清單 https://cloud.google.com/anthos/docs/resources/partner-storage["請按這裡"^]。

NetApp每季都會定期遵循法規要求、以驗證我們符合Astra Trident SCSI標準的儲存協調程式、ONTAP 以及我們的不含Anthos版本的不含更新功能的儲存系統。

下表包含NetApp與NetApp合作夥伴工程師所測試的Anthos版本、以驗證NetApp Astra Trident SCSI驅動程式與功能集、作為Anthos Ready儲存合作夥伴方案的一部分：

|===


| 部署類型 | 版本 | 儲存系統 | Astra Trident版本 | 傳輸協定 | 功能 


| VMware | 1.14 | 零點9.12.1. ONTAP | 23.01 | NAS | 多寫入器、Volume Expansion、Snapshot、PVCDataSource 


| VMware | 1.14 | 零點9.12.1. ONTAP | 23.01 | SAN | 原始區塊、Volume擴充、快照、PVCDataSource 


| VMware | 1.13. | 零點9.12.1. ONTAP | 22.10. | NAS | 多寫入器、Volume Expansion、Snapshot、PVCDataSource 


| VMware | 1.13. | 零點9.12.1. ONTAP | 22.10. | SAN | 原始區塊、Volume擴充、快照、PVCDataSource 


| VMware | 1.11. | 部分9.9.1 ONTAP | 22.04 | NAS | 多寫入器、Volume Expansion、快照 


| VMware | 1.11. | 部分9.9.1 ONTAP | 22.04 | SAN | 原始區塊、Volume擴充、快照 


| VMware | 1.11. | 元件12.3. | 22.04 | SAN | 原始區塊、Volume擴充、快照 


| 裸機 | 1.10 | 部分9.8 ONTAP | 22.01 | NAS | 多寫入器、Volume Expansion、快照 


| 裸機 | 1.10 | 部分9.8 ONTAP | 22.01 | SAN | 原始區塊、Volume擴充、快照 
|===


== NetApp儲存整合

NetApp提供多種產品、協助您協調及管理容器型環境（例如Anthos）中的持續資料。

NetApp Astra Trident是一款開放原始碼、完全支援的儲存協調工具、適用於容器和Kubernetes配送、包括Anthos。如需詳細資訊、請造訪Astra Trident網站 https://docs.netapp.com/us-en/trident/index.html["請按這裡"]。

下列頁面提供NetApp產品的其他資訊、這些產品已通過NetApp解決方案的Anthos應用程式與持續儲存管理的驗證。

link:a-w-n_overview_trident.html["下一步：NetApp Astra Trident總覽。"]
