---
sidebar: sidebar 
permalink: vmw-sc/sc-use-cases.html 
keywords: NetApp Solutions, vmware, sovereign cloud, netapp, use case 
summary:  
---
= NetApp 搭配 VMware Sovereign Cloud ：使用案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 整合多項 NetApp 技術、支援 VMware Sovereign Cloud 概念。

請使用下列連結、深入瞭解 NetApp 技術與 VMware Sovereign Cloud 的整合：

* link:#storageGRID["NetApp StorageGRID 做為物件存放區延伸"]




== NetApp StorageGRID 做為物件存放區延伸

NetApp 與 VMware 合作、將 NetApp StorageGRID 整合至 VMware Cloud Director 、以支援 VMware Sovereign Cloud 。此 VMware Cloud Director 外掛程式可讓服務供應商將 StorageGRID 當作物件儲存產品（無論使用案例為何）、並可透過服務供應商用來管理其產品目錄其他部分的相同 VMware 多租戶解決方案（ VMware Cloud Director ）來進行 StorageGRID 管理。

提供 VMware Sovereign 雲端的合作夥伴可以選擇 NetApp StorageGRID 來協助他們以非結構化資料來管理和維護雲端環境。其原生支援業界標準 API （例如 Amazon S3 API ）的通用相容性、有助於確保不同雲端環境之間的互通性順暢、而自動化生命週期管理等獨特創新技術則有助於確保更具成本效益的保護、儲存及長期維護客戶的非結構化資料。

NetApp 的 Sovereign Cloud 與 Cloud Director 供應商客戶的整合：

* 確保敏感資料（包括中繼資料）仍受到主權控制、同時防止外國主管機關存取可能違反資料隱私權法律的資料。
* 提高安全性與法規遵循能力、保護應用程式與資料不受瞬息萬變的攻擊模式影響、同時維持與值得信賴的本機持續相容。基礎架構、內建架構及當地專家。
* 符合未來需求的基礎架構、可快速因應瞬息萬變的資料隱私法規、安全威脅及地緣政治。
* 透過安全的資料共享與分析、在不違反隱私權法律的情況下推動創新、進而充分發揮資料價值。資料完整性受到保護、以確保獲得準確的洞見。


如需 StorageGRID 整合的詳細資訊、請參閱下列項目：

* link:https://www.netapp.com/newsroom/press-releases/news-rel-20231107-561294/["NetApp 公告"]

