---
sidebar: sidebar 
permalink: containers/a-w-n_solution_overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: 本參考文件提供Anthos with NetApp解決方案的部署驗證、部署於多個資料中心環境、並已通過NetApp與我們的工程合作夥伴的驗證。 
---
= NVA-1165：Anthos與NetApp合作
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


NetApp的Banu Sundhar和Suresh Thoppan

[role="lead"]
本參考文件提供NetApp與工程合作夥伴在多個資料中心環境中部署Anthos with NetApp解決方案時的部署驗證。此外、它也會使用 Trident Storage Orchestrator 來管理持續儲存設備、詳細說明與 NetApp 儲存系統的儲存整合。最後、我們會探索並記錄許多解決方案驗證和實際使用案例。



== 使用案例

Anthos with NetApp解決方案的架構旨在為具有下列使用案例的客戶提供卓越價值：

* 使用隨附的「bmctl」工具部署在裸機上、或使用VMware vSphere上的「gkectl」工具、即可輕鬆部署及管理Anthos環境。
* 結合企業容器和虛擬化工作負載的強大威力、以及部署在vSphere上或裸機上的Anthos https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["Kubevirt"^]。
* 實際組態和使用案例強調了 Anthos 功能、與 NetApp 儲存設備搭配使用、以及 Kubernetes 的開放原始碼儲存協調器 Trident 。




== 商業價值

企業逐漸採用DevOps實務來建立新產品、縮短發行週期、並快速新增新功能。由於容器和微服務的本質天生敏捷、因此在支援DevOps實務做法上扮演著重要角色。然而、在企業環境中以正式作業規模實作DevOps、卻帶來了自身的挑戰、並對基礎架構提出特定要求、例如：

* 堆疊中所有層級的高可用度
* 易於部署的程序
* 不中斷營運與升級
* API導向且可程式化的基礎架構、可跟上微服務敏捷度的腳步
* 多租戶共享、效能保證
* 同時執行虛擬化與容器化工作負載的能力
* 能夠根據工作負載需求獨立擴充基礎架構


Anthos with NetApp解決方案瞭解這些挑戰、並提供解決方案、在客戶所選的資料中心環境中實作Anthos的全自動部署、以協助解決每個疑慮。



== 技術總覽

Anthos with NetApp解決方案包含下列主要元件：



=== Anthos on Prem

Anthos on Prem是完全受支援的企業Kubernetes平台、可部署在VMware vSphere Hypervisor或您選擇的裸機基礎架構上。

如需更多關於Anthos的資訊、請參閱Anthos網站 https://cloud.google.com/anthos["請按這裡"^]。



=== NetApp儲存系統

NetApp擁有多種儲存系統、最適合用於企業資料中心和混合雲部署。NetApp 產品組合包括 NetApp ONTAP 、 Cloud Volumes ONTAP 、 Cloud Volumes Service 、 Azure NetApp Files 、適用於 NetApp ONTAP 儲存系統的 FSX ONTAP 、所有這些產品都能為容器化應用程式提供持續儲存。

如需詳細資訊、請參閱NetApp網站 https://www.netapp.com["請按這裡"]。



=== NetApp儲存整合

Trident 是一款開放原始碼且完全支援的儲存協調工具、適用於容器和 Kubernetes 配送、包括 Anthos 。

有關詳細信息，請訪問 Trident 網站 https://docs.netapp.com/us-en/trident/index.html["請按這裡"]。



== 進階組態選項

本節專供實際使用者在將此解決方案部署至正式作業環境時可能需要執行的自訂作業、例如建立專用的私有映像登錄或部署自訂負載平衡器執行個體。



== 已驗證版本的目前支援對照表

請參閱 https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["請按這裡"] 以取得已驗證版本的支援對照表。
