---
sidebar: sidebar 
permalink: containers/a-w-n_LB_MetalLB.html 
summary: 本頁詳細說明MetalLB負載平衡器的安裝與組態指示。 
keywords: Anthos, Kubernetes, MetalLB, LoadBalancer, Astra, Astra Control Center 
---
= 安裝MetalLB負載平衡器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本頁列出MetalLB託管負載平衡器的安裝與組態指示。



== 安裝MetalLB負載平衡器

MetalLB負載平衡器與VMware上的Anthos叢集完全整合、並從1.11版開始、在管理與使用者叢集設定中執行自動化部署。您必須在各自的「叢集.yaml」組態檔中修改文字區塊、才能提供負載平衡器資訊。它是在您的Anthos叢集上自行代管、而不需要像其他支援的負載平衡器解決方案那樣部署外部資源。它也可讓您建立IP集區、以便在未在雲端供應商上執行的叢集中、建立類型負載平衡器的Kubernetes服務、自動指派位址。



== 與Anthos整合

啟用Anthos管理的MetalLB負載平衡器時、您必須修改「admin-cluster．yaml」檔案中「loadbalancer：」區段中的幾行。您唯一必須修改的值是設定「controlPlueVIP:」位址、然後將「種類：」設為MetalLB。請參閱下列程式碼片段以取得範例：

[listing]
----
# (Required) Load balancer configuration
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.230"
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----
在為Anthos使用者叢集啟用MetalLB負載平衡器時、每個「user-cluster．yaml」檔案中有兩個區域必須更新。首先、您必須以類似「admin-cluster．yaml」檔案的方式、修改「controlPlaeVIP：」、「ingressVIP：」和「in種類：」等「負載平衡器：」區段中的值。請參閱下列程式碼片段以取得範例：

[listing]
----
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.240"
    # Shared by all services for ingress traffic
    ingressVIP: "10.61.181.244"
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----

NOTE: 擷取VIP IP位址必須存在於稍後在組態中指派給MetalLB負載平衡器的IP位址集區內。

然後您需要瀏覽至「metalLB:」子區段、並在「-name:」變數中命名Pool來修改「addressPools：」區段。您也必須為「Addresses：」變數提供範圍、建立一個IP位址集區、以便MetalLB指派給類型負載平衡器的服務。

[listing]
----
# # (Required when using "MetalLB" kind in user clusters) Specify the MetalLB config
 metalLB:
 #   # (Required) A list of non-overlapping IP pools used by load balancer typed services.
 #   # Must include ingressVIP of the cluster.
    addressPools:
 #   # (Required) Name of the address pool
    - name: "default"
 #     # (Required) The addresses that are part of this pool. Each address must be either
 #     # in the CIDR form (1.2.3.0/24) or range form (1.2.3.1-1.2.3.5).
      addresses:
      - "10.61.181.244-10.61.181.249"
----

NOTE: 位址集區可以像範例中所示的範圍來提供、將其限制為特定子網路中的多個位址、或者如果整個子網路都可用、則可將其作為CIDR表示法來提供。

. 當建立負載平衡器類型的Kubernetes服務時、MetalLB會自動指派外部IP給服務、並回應ARP要求來通告IP位址。

