---
sidebar: sidebar 
permalink: containers/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: NetApp與Google Cloud已有多年的穩固關係、NetApp率先推出雲端資料服務給Google Cloud Cloud Volumes ONTAP 、其中包含了使用支援功能的支援功能、以及使用功能完善Cloud Volumes Service 的功能。接著、我們驗證NetApp HCI 了適用於內部部署的Google Cloud Anthos（以Hypervisor為基礎的混合式多雲端Kubernetes解決方案、部署在VMware vSphere上）的VMware平台、藉此擴大這種關係。NetApp接著通過了Anthos Ready的NetApp Trident、ONTAP Dynamic及NFS傳輸協定資格、為容器提供動態持續儲存。 
---
= WP-7337：裸機上的安索斯
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp公司Alan Cowles和NIKhil M Kulkarni

NetApp與Google Cloud已有多年的穩固關係、NetApp率先推出雲端資料服務、適用於具備Cloud Volumes ONTAP 支援功能的Google Cloud with動動動動地和Cloud Volumes Service 支援功能的整個過程。接著、我們驗證NetApp HCI 了適用於內部部署的Google Cloud Anthos（以Hypervisor為基礎的混合式多雲端Kubernetes解決方案、部署在VMware vSphere上）的VMware平台、藉此擴大這種關係。NetApp接著通過了Anthos Ready的NetApp Trident、ONTAP Dynamic及NFS傳輸協定資格、為容器提供動態持續儲存。

現在、Anthos可以直接安裝在客戶環境中的裸機伺服器上、這也為客戶增加了額外的選項、讓他們無需Hypervisor就能將Google Cloud延伸至其本機資料中心。此外、藉由運用NetApp ONTAP 的NetApp支援儲存作業系統與NetApp Trident的功能、您可以整合容器的持續儲存設備、來擴充平台的功能。

這項組合可讓您充分發揮伺服器、儲存設備和網路的完整潛力、並結合Google Cloud提供的支援、服務層級、每月計費和隨選彈性。由於您使用自己的硬體、網路和儲存設備、因此您可以直接控制應用程式的規模、安全性和網路延遲、並享有以裸機Anthos為基礎的託管與容器化應用程式的優點。

link:bmanthos_solution_overview.html["下一步：解決方案總覽。"]
