---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= 影片與示範：Red Hat OpenShift with NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
下列影片示範本文件所述的部分功能

.使用 Trident Protect 為虛擬機器進行災難恢復
video::ae4bdcf7-b344-4f19-89ed-b2d500f94efd[panopto,width=360]
.使用 Trident Protect 保護虛擬機器
video::4670e188-3d67-4207-84c5-b2d500f934a0[panopto,width=360]
.使用 iSCSI 儲存設備在 OpenShift 虛擬化中建立 VM
video::497b868d-2917-4824-bbaa-b2d500f92dda[panopto,width=360]
.使用 Red Hat 認證 Trident 營運商安裝 Trident
video::15c225f3-13ef-41ba-b255-b2d500f927c0[panopto,width=360]
.Amazon FSX for NetApp ONTAP 搭配使用託管控制平面的 AWS 上的 Red Hat OpenShift 服務
video::213061d2-53e6-4762-a68f-b21401519023[panopto,width=360]
.透過適用於 NetApp ONTAP 的 Amazon FSX 、在 ROSA 上以 OpenShift 虛擬化技術即時移轉虛擬機器
video::4b3ef03d-7d65-4637-9dab-b21301371d7d[panopto,width=360]
.可在 OpenShift 叢集上部署 Trident 並建立儲存類別的 Ansible 自動化功能
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
link:https://github.com/NetApp/trident-install["您可以在 GitHub 中找到使用 Ansible 安裝 NetApp Trident 、 StorageClasses 和 Backend 的教戰手冊。"]

.使用 ONTAP SAN （ iSCSI ）儲存類別、在 OpenShift 虛擬化中部署新的 VM
video::2e2c6fdb-4651-46dd-b028-b1ed00d37da3[panopto,width=360]
.使用 ONTAP NAS 儲存類部署 PostgreSQL Container 應用程式
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]
.Cloud Insights 與 Openshift 虛擬化整合
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.使用 Red Hat MTV 將 VM 移轉至使用 NetApp ONTAP 儲存設備的 OpenShift 虛擬化
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.使用 Trident 的進階資料管理功能、容錯移轉 / 容錯回復 OpenShift VM （僅提供早期存取方案）
video::f2a8fa24-2971-4cdc-9bbb-b1f1007032ea[panopto,width=360]
.Cloud Insights 與 Openshift 虛擬化整合
video::29ed6938-eeaf-4e70-ae7b-b15d011d75ff[panopto,width=360]
.可在 OpenShift 叢集上部署 Trident 並建立儲存類別的 Ansible 自動化功能
video::fae6605f-b61a-4a34-a97f-b1ed00d2de93[panopto,width=360]
** GitHub 中的 Ansible 程式碼範例 **link:https://github.com/NetApp/trident-install["您可以在 GitHub 中找到使用 Ansible 安裝 NetApp Trident 、 StorageClasses 和 Backend 的教戰手冊。"]

.使用 ONTAP NAS 儲存類部署 PostgreSQL Container 應用程式
video::d3eacf8c-888f-4028-a695-b1ed00d28dee[panopto,width=360]
.工作負載移轉：採用NetApp的Red Hat OpenShift
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.安裝OpenShift虛擬化：採用NetApp的Red Hat OpenShift
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.部署採用OpenShift虛擬化技術的虛擬機器-採用NetApp的Red Hat OpenShift
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.NetApp HCI for Red Hat OpenShift on Red Hat 虛擬化
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]