---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_deployment_prerequisites.html 
keywords: OpenShift, OCP, Astra Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: Red Hat OpenShift虛擬化搭配NetApp ONTAP 產品 
---
= 部署Red Hat OpenShift虛擬化技術搭配NetApp ONTAP 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本節詳細說明如何使用 NetApp ONTAP 部署 Red Hat OpenShift 虛擬化。



== 先決條件

* Red Hat OpenShift叢集（高於版本4.6）安裝在裸機基礎架構上、並具有RHCOOS工作節點
* OpenShift叢集必須透過安裝程式提供的基礎架構（IPI）進行安裝
* 部署機器健全狀況檢查以維護VM的HA
* NetApp ONTAP 的叢集
* 安裝在OpenShift叢集上的Astra Trident
* Trident後端在ONTAP 叢集上設定SVM
* OpenShift叢集上設定的StorageClass、其中Astra Trident為資源配置程式
* 叢集管理存取Red Hat OpenShift叢集
* 管理員存取NetApp ONTAP 解決方案叢集
* 安裝了tridentctl和occ工具並新增至$path的管理工作站


由於OpenShift虛擬化是由安裝在OpenShift叢集上的操作員所管理、因此會對記憶體、CPU和儲存設備產生額外的負荷、因此在規劃叢集的硬體需求時、必須將這些負荷列入考量。請參閱文件 https://docs.openshift.com/container-platform/4.7/virt/install/preparing-cluster-for-virt.html#virt-cluster-resource-requirements_preparing-cluster-for-virt["請按這裡"] 以取得更多詳細資料。

或者、您也可以設定節點放置規則、以指定OpenShift叢集節點的子集來裝載OpenShift虛擬化操作員、控制器和VM。若要設定OpenShift虛擬化的節點放置規則、請遵循文件 https://docs.openshift.com/container-platform/4.7/virt/install/virt-specifying-nodes-for-virtualization-components.html["請按這裡"]。

對於支援OpenShift虛擬化的儲存設備、NetApp建議使用專屬StorageClass、從特定Trident後端要求儲存設備、然後再由專屬SVM提供支援。這可維持多租戶層級、以處理OpenShift叢集上VM型工作負載所需的資料。
