---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= 影片與示範：Red Hat OpenShift with NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
下列影片示範本文件所述的部分功能：

.利用 Astra Control 和 NetApp FlexClone 技術加速軟體開發 - Red Hat OpenShift with NetApp
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.運用NetApp Astra Control執行事後分析及還原您的應用程式
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Astra Control Center 提供 CI/CD 管線中的資料保護功能
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.使用 Astra Control Center 進行工作負載移轉： Red Hat OpenShift with NetApp
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.工作負載移轉：採用NetApp的Red Hat OpenShift
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.安裝OpenShift虛擬化：採用NetApp的Red Hat OpenShift
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.部署採用OpenShift虛擬化技術的虛擬機器-採用NetApp的Red Hat OpenShift
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.NetApp HCI for Red Hat OpenShift on Red Hat 虛擬化
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]