---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: 繪圖工作站通常用於製造業、醫療業、能源、媒體與娛樂業、教育、 架構等。對於圖形密集型應用程式而言、行動性通常受到限制。 
---
= 產業解決方案
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
繪圖工作站通常用於製造業、醫療業、能源、媒體與娛樂業、教育、 架構等。對於圖形密集型應用程式而言、行動性通常受到限制。

為了解決行動性問題、虛擬桌面服務為所有類型的員工提供桌面環境、從工作人員到專家使用者、使用雲端或NetApp HCI 搭配使用的硬體資源、包括靈活GPU組態的選項。VDS可讓使用者透過筆記型電腦、平板電腦及其他行動裝置、從任何位置存取工作環境。

若要以ANSYS Fluent、ANSYS機械、Autodesk AutoCad、Autodesk Inventor、Autodesk 3ds Max等軟體執行製造工作負載、 Dassault Syst è mes SOLIDWORKS、Dassault Syst è mes CATIA、PTC Creo、Siemens PLM NX等、 下表列出各種雲端上可用的GPU（截至2021年1月為止）。

[cols="20%, 20%, 20%, 20%, 20%"]
|===
| GPU模型 | Microsoft Azure | Google運算（GCP） | Amazon Web Services（AWS） | 內部部署（NetApp HCI 僅限內部部署） 


| NVIDIA M60 | 是的 | 是的 | 是的 | 否 


| NVIDIA T4 | 否 | 是的 | 是的 | 是的 


| NVIDIA P100 | 否 | 是的 | 否 | 否 


| NVIDIA P4 | 否 | 是的 | 否 | 否 
|===
也可與其他使用者共用桌面工作階段、以及專屬的個人桌面。虛擬桌面可以有一到四個GPU、或是使用NetApp HCI 部分GPU搭配使用。NVIDIA T4是一款多功能GPU卡、可滿足各種使用者工作負載的需求。每張NetApp HCI GPU卡的每張E64H615C都有16GB的影格緩衝記憶體、每部伺服器有三張卡。單一H615C伺服器上可裝載的使用者數量取決於使用者工作負載。

[cols="25%, 25%, 25%, 25%"]
|===
| 使用者/伺服器 | 輕量（4GB） | 中型（8GB） | 重磅（16GB） 


| H615C | 12. | 6. | 3. 
|===
若要判斷使用者類型、請在使用者使用執行一般工作的應用程式時、執行GPU剖析工具。GPU剖析器可擷取記憶體需求、顯示器數量及使用者所需的解析度。接著您可以挑選符合需求的vGPU設定檔。

使用GPU的虛擬桌面可支援高達8K的顯示解析度、公用程式nView可將單一監視器分割成多個區域、以便使用不同的資料集。

利用檔案儲存功能、您可以實現下列效益：ONTAP

* 單一命名空間可擴充至20PB的儲存容量、內含4、000億個檔案、無需大量的管理輸入
* 可透過全域檔案快取跨越地球的命名空間
* 利用託管NetApp儲存設備實現安全的多租戶共享
* 使用NetApp FabricPool 解決方案將冷資料移轉至物件存放區
* 利用檔案系統分析快速建立檔案統計資料
* 將儲存叢集擴充至最多24個節點、以提升容量與效能
* 能夠使用配額來控制儲存空間、並以QoS限制來保證效能
* 以加密保護資料安全
* 滿足廣泛的資料保護與法規遵循需求
* 提供靈活的營運不中斷選項


link:vdi-vds/hcvdivds_conclusion.html["下一步：結論"]
