---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: 使用H610C或H615C時、GPU的授權必須向授權經銷授權的NVIDIA合作夥伴購買。 
---
= NVIDIA授權
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
使用H610C或H615C時、GPU的授權必須向授權經銷授權的NVIDIA合作夥伴購買。您可以使用找到NVIDIA合作夥伴 https://["合作夥伴搜尋工具"^]。搜尋虛擬GPU（vGPU）或Tesla等專長能力。

NVIDIA vGPU軟體共有四種版本：

* NVIDIA GRID虛擬PC（Grid vPC）
* NVIDIA Grid虛擬應用程式（Grid vApp）
* NVIDIA Quadro虛擬資料中心工作站（Quadro vDWS）
* NVIDIA虛擬伺服器（vComputeServer）




== Grid Virtual PC

本產品非常適合想要虛擬桌面的使用者、因為它能為Microsoft Windows應用程式、瀏覽器、高畫質視訊及多重監視器支援提供絕佳的使用者體驗。NVIDIA GRID Virtual PC可在虛擬環境中提供原生體驗、讓您以完整效能執行所有的PC應用程式。



== Grid虛擬應用程式

Grid vApp適用於部署遠端桌面工作階段主機（RDSH）或其他應用程式串流或工作階段型解決方案的組織。專為以完整效能提供Microsoft Windows應用程式而設計、Grid vApp也支援Windows Server託管的RDSH桌面。



== Quadro虛擬資料中心工作站

此版本非常適合主流和高階設計師、他們使用強大的3D內容建立應用程式、例如Dassault CATIA、SOLIDWORKS、3dexitite、Siemens NX、PTC Creo、 Schlumberger Petrel或Autodesk Maya。NVIDIA Quadro vDWS可讓使用者在任何裝置上、都能以完整的功能和效能存取專業的圖形應用程式。



== NVIDIA虛擬伺服器

許多組織執行運算密集的伺服器工作負載、例如人工智慧（AI）、深度學習（DL）和資料科學。在這些使用案例中、NVIDIA vComputeServer軟體可將NVIDIA GPU虛擬化、以錯誤修正程式碼、分頁淘汰、透過NVLink點對點、以及多vGPU等功能來加速運算密集的伺服器工作負載。


NOTE: Quadro vDWS授權可讓您使用GRID vPC和NVIDIA vComputerServer。

link:hcvdivds_deployment.html["下一步：部署"]
