---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_why_ontap.html 
keywords: VDS, Virtual Desktop Service, ONTAP, FlexGroup, File System analytics, cloud tiering, global namespace 
summary: 虛擬桌面服務的功能。ONTAP 
---
= 虛擬桌面服務的功能ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
下列功能可讓IT成為虛擬桌面服務的理想選擇。ONTAP

* *橫向擴充檔案系統* ONTAP FlexGroup 。*不實磁碟區的大小可擴充至20PB以上、而且可在單一命名空間內容納4000多億個檔案。叢集最多可包含24個儲存節點、每個節點可根據所使用的機型靈活調整網路介面卡數量。
+
使用者的虛擬桌面、主資料夾、使用者設定檔容器、共用資料等、都能隨需擴充、不需擔心檔案系統的限制。

* *檔案系統分析。*您可以使用XCP工具深入瞭解共享資料。有了支援功能的支援功能、您可以輕鬆查詢及擷取檔案中繼資料資訊、並識別冷資料。ONTAP
* *雲端分層。*您可以將冷資料移轉至雲端的物件存放區、或移轉至資料中心的任何S3相容儲存區。
* *檔案版本。*使用者可以恢復受NetApp ONTAP SSnapshot複本保護的檔案。由於Snapshot複本只記錄變更的區塊、因此空間效率極高。ONTAP
* * Global namespacy.* ONTAP FlexCache 支援遠端快取檔案儲存設備、因此可更輕鬆地管理包含ONTAP 此功能的各個位置的共享資料。
* *安全的多租戶支援。*單一實體儲存叢集可呈現為多個虛擬儲存陣列、每個陣列都有自己的磁碟區、儲存傳輸協定、邏輯網路介面、身分識別與驗證網域、管理使用者等。因此、您可以在多個業務單位或環境（例如測試、開發和正式作業）之間共享儲存陣列。
+
為了保證效能、您可以使用調適性QoS來根據已使用或已分配的空間來設定效能層級、也可以使用配額來控制儲存容量。

* * VMware整合。* ONTAP VMware vSphere的支援功能可提供vCenter外掛程式、以配置資料存放區、實作vSphere主機最佳實務做法、以及監控ONTAP 各項資源。
+
支援用於陣列整合（VAAI）的vStorage API、將SCSI /檔案作業卸載至儲存陣列。ONTAP此外、支援用於儲存感知（VASA）的vStorage API、以及同時支援區塊和檔案傳輸協定的虛擬Volume。ONTAP

+
VMware vSphere的VMware vCenter外掛程式可讓您使用儲存陣列上的Snapshot功能、輕鬆備份及還原虛擬機器。SnapCenter

+
ActiveIQ Unified Manager可在vSphere環境中提供端點對端點儲存網路可見度。系統管理員可以輕鬆識別ONTAP 任何可能在執行於NetApp的虛擬桌面環境中發生的延遲問題。

* *安全性法規遵循*。*有了ActiveIQ Unified Manager、您可以監控多ONTAP 個含有任何違反原則警示的支援系統。
* *多重傳輸協定支援。* ONTAP 支援區塊（iSCSI、FC、FCoE和NVMe/FC）、檔案（NFSv3、 NFSv4.1、SMB2.x和SMB3.x）、以及物件（S3）儲存傳輸協定。
* *自動化支援。* ONTAP 支援功能提供REST API、Ansible和PowerShell模組、以使用VDS管理入口網站來自動化工作。


link:hcvdivds_data_management.html["下一步：資料管理"]
