---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 本頁提供影片和教學課程的簡介。 
---
= 混合雲、虛擬化與容器影片與示範
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
請觀看下列影片和示範、重點介紹混合雲、虛擬化和容器解決方案的特定功能。

.適用於VMware vSphere的NetApp ONTAP 產品開發工具
[%collapsible]
====
.VMware適用的VMware工具-總覽ONTAP
[%collapsible]
=====
video::otv_overview.mp4[]
=====
.VMware iSCSI Datastore隨ONTAP 需配置
[%collapsible]
=====
video::otv_iscsi_provision.mp4[]
=====
.VMware NFS資料存放區資源配置ONTAP 功能
[%collapsible]
=====
video::otv_nfs_provision.mp4[]
=====
====
.VMware Cloud on AWS搭配AWS FSX for NetApp ONTAP 功能
[%collapsible]
====
.Windows Guest連線儲存設備搭配ONTAP 使用iSCSI的FSX功能
[%collapsible]
=====
video::vmc_windows_vm_iscsi.mp4[]
=====
.Linux Guest連線儲存設備搭配ONTAP 使用NFS的FSX功能
[%collapsible]
=====
video::vmc_linux_vm_nfs.mp4[]
=====
.採用Amazon FSX for NetApp ONTAP 的VMware Cloud on AWS TCO節約效益
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC-TCO-calculator.mp4[]
=====
.VMware Cloud on AWS補充資料存放區搭配Amazon FSX for NetApp ONTAP
[%collapsible]
=====
video::FSxN-NFS-Datastore-on-VMC.mp4[]
=====
.VMware Cloud on AWS移轉至FSxN、VMware HCX
[%collapsible]
=====
video::VMC_HCX_Setup.mp4[]
video::Migration_HCX_VMC_FSxN_VMotion.mp4[]
video::Migration_HCX_VMC_FSxN_cold_migration.mp4[]
=====
====
.Azure上的Azure VMware Services Azure NetApp Files with VMware（ANF）
[%collapsible]
====
.Azure VMware解決方案補充資料存放區總覽Azure NetApp Files （含）
[%collapsible]
=====
video::ANF-NFS-datastore-on-AVS.mp4[]
=====
.Azure VMware解決方案DR Cloud Volumes ONTAP 搭配VMware功能、包括功能不完整、SnapCenter 功能完整
[%collapsible]
=====
video::AVS-guest-connect-DR-use-case.mp4[]
=====
.Azure VMware解決方案移轉至Anf、VMware HCX
[%collapsible]
=====
video::Migration_HCX_AVS_ANF_ColdMigration.mp4[]
video::Migration_HCX_AVS_ANF_VMotion.mp4[]
video::Migration_HCX_AVS_ANF_Bulk.mp4[]
=====
====
.VMware vSphere的插件SnapCenter
[%collapsible]
====
NetApp SnapCenter 流通軟體是易於使用的企業平台、可安全地協調及管理應用程式、資料庫及檔案系統之間的資料保護。

VMware vSphere的《VMware vSphere支援VMware外掛程式」SnapCenter 可讓您針對VM執行備份、還原及附加作業、以及SnapCenter 針對直接在VMware vCenter內以「VMware vCenter」登錄的資料存放區執行備份與掛載作業。

如需有關SnapCenter 適用於VMware vSphere的NetApp解決方案外掛程式的詳細資訊、請參閱 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["適用於VMware vSphere的NetApp SnapCenter 功能外掛程式總覽"]。

.VMware vSphere的解決方案外掛程式-解決方案先決條件SnapCenter
[%collapsible]
=====
video::scv_prereq_overview.mp4[]
=====
.VMware vSphere的VMware外掛程式- SnapCenter 部署
[%collapsible]
=====
video::scv_deployment.mp4[]
=====
.VMware vSphere的VMware外掛程式-備份工作流程SnapCenter
[%collapsible]
=====
video::scv_backup_workflow.mp4[]
=====
.VMware vSphere的VMware外掛程式-還原工作流程SnapCenter
[%collapsible]
=====
video::scv_restore_workflow.mp4[]
=====
.支援SQL還原工作流程SnapCenter
[%collapsible]
=====
video::scv_sql_restore.mp4[]
=====
====
.NetApp與VMware Tanzu合作
[%collapsible]
====
VMware Tanzu可讓客戶透過vSphere或VMware Cloud Foundation來部署、管理及管理Kubernetes環境。VMware產品組合可讓客戶從單一控制面板管理所有相關的Kubernetes叢集、選擇最符合需求的VMware Tanzu版本。

如需VMware Tanzu的詳細資訊、請參閱 https://tanzu.vmware.com/tanzu["VMware Tanzu概述"^]。本審查涵蓋使用案例、可用的新增項目、以及有關VMware Tanzu的更多資訊。

* https://www.youtube.com/watch?v=ZtbXeOJKhrc["如何將vVols與NetApp和VMware Tanzu Basic搭配使用、第1部分"^]
* https://www.youtube.com/watch?v=FVRKjWH7AoE["如何搭配NetApp和VMware Tanzu Basic使用vVols、第2部分"^]
* https://www.youtube.com/watch?v=Y-34SUtTTtU["如何搭配NetApp和VMware Tanzu Basic使用vVols、第3部分"^]


====
.採用Red Hat OpenShift的NetApp
[%collapsible]
====
Red Hat OpenShift是一款企業Kubernetes平台、可讓您以開放式混合雲策略來執行以容器為基礎的應用程式。Red Hat OpenShift可在領先業界的公有雲或自助管理軟體上作為雲端服務提供客戶在設計容器型解決方案時所需的靈活度。

如需Red Hat OpenShift的詳細資訊、請參閱此 https://www.redhat.com/en/technologies/cloud-computing/openshift["Red Hat OpenShift總覽"^]。您也可以檢閱產品文件和部署選項、深入瞭解Red Hat OpenShift。

* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_workload_migration_manual.html["工作負載移轉：採用NetApp的Red Hat OpenShift"^]
* https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_videos_RHV_deployment.html["在RHV上部署Red Hat OpenShift：搭配NetApp的Red Hat OpenShift"^]


====