---
sidebar: sidebar 
permalink: virtualization/vsphere_admin_introduction.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 本頁說明在ONTAP VMware vSphere環境中實作NetApp解決方案的最佳實務做法。 
---
= vSphere管理員適用的功能介紹ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== 為何ONTAP 選擇適用於vSphere的呢？

NetApp ONTAP 功能可簡化儲存與資料管理作業、無論是在內部部署或雲端部署、都能為VMware環境帶來顯著的輔助。NetApp同級最佳的資料保護、儲存效率創新技術、以及以SAN和NAS為基礎的VMware架構所提供的卓越效能、是數萬家客戶選擇ONTAP 使用VMware作為vSphere部署儲存解決方案的原因之一。

NetApp提供多種VMware產品的VMware外掛程式、驗證及資格、以支援面臨管理虛擬化環境的獨特挑戰的客戶。NetApp的儲存與資料管理功能與VMware的虛擬化功能相同、可讓客戶專注於核心能力、而非管理實體儲存設備。VMware與NetApp之間的這種將近20年的合作關係持續演進、隨著VMware Cloud Foundation與Tanzu等新技術的興起、客戶的價值也隨之提高、同時持續支援vSphere的基礎。

客戶重視的關鍵因素包括：

* *統一化儲存設備*
* *儲存效率*
* *虛擬磁碟區與儲存原則型管理*
* *混合雲*


如需有關支援的NetApp與VMware解決方案的詳細資訊、請參閱下列資源：

* https://mysupport.netapp.com/matrix/#welcome["NetApp互通性對照表工具"^] （僅限部分）IMT 。此功能定義了可用來建置FC/FCoE、iSCSI、NFS和CIFS組態的合格元件和版本。IMT
* https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san&details=1&partner=64&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["《VMware相容性指南》"^]。VMware相容性指南列出系統、I/O、儲存/SAN及備份與VMware Infrastructure和軟體產品的相容性
* https://www.netapp.com/support-and-training/documentation/ontap-tools-for-vmware-vsphere-documentation/["適用於ONTAP VMware的NetApp產品開發工具"^]。VMware vSphere的VMware vSphere工具是單一vCenter Server外掛程式、其中包含VSC、VASA Provider及儲存複寫介面卡（SRA）擴充功能。ONTAP

