---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 本頁提供影片和教學課程的簡介。 
---
= 虛擬化影片與示範
:hardbreaks:
:allow-uri-read: 
:firstname: = Virtualization Videos and Demos
:author: = Virtualization Videos and Demos
:authorinitials: =
:authors: = Virtualization Videos and Demos
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
請觀看下列影片和示範、重點介紹混合雲、虛擬化和容器解決方案的特定功能。

.適用於VMware vSphere的NetApp ONTAP 產品開發工具
[%collapsible]
====
.VMware適用的VMware工具-總覽ONTAP
video::d2ac19ba-28c4-4c07-8724-b01200f99845[panopto]
.VMware iSCSI Datastore隨ONTAP 需配置
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.VMware NFS資料存放區資源配置ONTAP 功能
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.VMware Cloud on AWS搭配AWS FSX for NetApp ONTAP 功能
[%collapsible]
====
.Windows Guest連線儲存設備搭配ONTAP 使用iSCSI的FSX功能
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.Linux Guest連線儲存設備搭配ONTAP 使用NFS的FSX功能
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.採用Amazon FSX for NetApp ONTAP 的VMware Cloud on AWS TCO節約效益
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud on AWS補充資料存放區搭配Amazon FSX for NetApp ONTAP
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.適用於VMC的VMware HCX部署與組態設定
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMware HCX for VMC 和 FSxN 的 VMotion 移轉示範
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMware HCX for VMC和FSxN的冷移轉示範
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.Azure上的Azure VMware Services Azure NetApp Files with VMware（ANF）
[%collapsible]
====
.Azure VMware解決方案補充資料存放區總覽Azure NetApp Files （含）
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Azure VMware解決方案DR Cloud Volumes ONTAP 搭配VMware功能、包括功能不完整、SnapCenter 功能完整
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX針對AVS和ANF進行冷移轉示範
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX針對AVS和ANF的VMotion示範
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.VMware HCX針對AVS和ANF的大量移轉示範
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.VMware vSphere的插件SnapCenter
[%collapsible]
====
NetApp SnapCenter 流通軟體是易於使用的企業平台、可安全地協調及管理應用程式、資料庫及檔案系統之間的資料保護。

VMware vSphere的《VMware vSphere支援VMware外掛程式」SnapCenter 可讓您針對VM執行備份、還原及附加作業、以及SnapCenter 針對直接在VMware vCenter內以「VMware vCenter」登錄的資料存放區執行備份與掛載作業。

如需有關SnapCenter 適用於VMware vSphere的NetApp解決方案外掛程式的詳細資訊、請參閱 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["適用於VMware vSphere的NetApp SnapCenter 功能外掛程式總覽"]。

.VMware vSphere的解決方案外掛程式-解決方案先決條件SnapCenter
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.VMware vSphere的VMware外掛程式- SnapCenter 部署
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.VMware vSphere的VMware外掛程式-備份工作流程SnapCenter
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.VMware vSphere的VMware外掛程式-還原工作流程SnapCenter
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.支援SQL還原工作流程SnapCenter
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.NetApp與VMware Tanzu合作
[%collapsible]
====
VMware Tanzu可讓客戶透過vSphere或VMware Cloud Foundation來部署、管理及管理Kubernetes環境。VMware產品組合可讓客戶從單一控制面板管理所有相關的Kubernetes叢集、選擇最符合需求的VMware Tanzu版本。

如需VMware Tanzu的詳細資訊、請參閱 https://tanzu.vmware.com/tanzu["VMware Tanzu概述"^]。本審查涵蓋使用案例、可用的新增項目、以及有關VMware Tanzu的更多資訊。

.如何將vVols與NetApp和VMware Tanzu Basic搭配使用、第1部分
video::ZtbXeOJKhrc[youtube,width=360]
.如何搭配NetApp和VMware Tanzu Basic使用vVols、第2部分
video::FVRKjWH7AoE[youtube,width=360]
.如何搭配NetApp和VMware Tanzu Basic使用vVols、第3部分
video::Y-34SUtTTtU[youtube,width=360]
====