---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 本頁提供影片和教學課程的簡介。 
---
= 虛擬化影片與示範
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
請觀看下列影片和示範、重點介紹混合雲、虛擬化和容器解決方案的特定功能。

.適用於VMware vSphere的NetApp ONTAP 產品開發工具
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
VMware適用的VMware工具-總覽ONTAP

 a| 
VMware iSCSI Datastore隨ONTAP 需配置

 a| 
VMware NFS資料存放區資源配置ONTAP 功能


|===
====
.VMware Cloud on AWS搭配AWS FSX for NetApp ONTAP 功能
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Windows Guest連線儲存設備搭配ONTAP 使用iSCSI的FSX功能

 a| 
Linux Guest連線儲存設備搭配ONTAP 使用NFS的FSX功能

 a| 
採用Amazon FSX for NetApp ONTAP 的VMware Cloud on AWS TCO節約效益




 a| 
VMware Cloud on AWS補充資料存放區搭配Amazon FSX for NetApp ONTAP

 a| 
適用於VMC的VMware HCX部署與組態設定

 a| 
VMware HCX for VMC 和 FSxN 的 VMotion 移轉示範




 a| 
VMware HCX for VMC和FSxN的冷移轉示範

 a| 
 a| 

|===
====
.Azure上的Azure VMware Services Azure NetApp Files with VMware（ANF）
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Azure VMware解決方案補充資料存放區總覽Azure NetApp Files （含）

 a| 
Azure VMware解決方案DR Cloud Volumes ONTAP 搭配VMware功能、包括功能不完整、SnapCenter 功能完整

 a| 
VMware HCX針對AVS和ANF進行冷移轉示範




 a| 
VMware HCX針對AVS和ANF的VMotion示範

 a| 
VMware HCX針對AVS和ANF的大量移轉示範

 a| 

|===
====
.VMware vSphere的插件SnapCenter
[%collapsible]
====
NetApp SnapCenter 流通軟體是易於使用的企業平台、可安全地協調及管理應用程式、資料庫及檔案系統之間的資料保護。

VMware vSphere的《VMware vSphere支援VMware外掛程式」SnapCenter 可讓您針對VM執行備份、還原及附加作業、以及SnapCenter 針對直接在VMware vCenter內以「VMware vCenter」登錄的資料存放區執行備份與掛載作業。

如需有關SnapCenter 適用於VMware vSphere的NetApp解決方案外掛程式的詳細資訊、請參閱 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["適用於VMware vSphere的NetApp SnapCenter 功能外掛程式總覽"]。

[cols="5a, 5a, 5a"]
|===


 a| 
VMware vSphere的解決方案外掛程式-解決方案先決條件SnapCenter

 a| 
VMware vSphere的VMware外掛程式- SnapCenter 部署

 a| 
VMware vSphere的VMware外掛程式-備份工作流程SnapCenter




 a| 
VMware vSphere的VMware外掛程式-還原工作流程SnapCenter

 a| 
支援SQL還原工作流程SnapCenter

 a| 

|===
====
.NetApp與VMware Tanzu合作
[%collapsible]
====
VMware Tanzu可讓客戶透過vSphere或VMware Cloud Foundation來部署、管理及管理Kubernetes環境。VMware產品組合可讓客戶從單一控制面板管理所有相關的Kubernetes叢集、選擇最符合需求的VMware Tanzu版本。

如需VMware Tanzu的詳細資訊、請參閱 https://tanzu.vmware.com/tanzu["VMware Tanzu概述"^]。本審查涵蓋使用案例、可用的新增項目、以及有關VMware Tanzu的更多資訊。

[cols="5a, 5a, 5a"]
|===


 a| 
如何將vVols與NetApp和VMware Tanzu Basic搭配使用、第1部分

video::ZtbXeOJKhrc[youtube,width=360] a| 
如何搭配NetApp和VMware Tanzu Basic使用vVols、第2部分

video::FVRKjWH7AoE[youtube,width=360] a| 
如何搭配NetApp和VMware Tanzu Basic使用vVols、第3部分

video::Y-34SUtTTtU[youtube,width=360]
|===
====