= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS支援下列組態的NetApp儲存設備：

* FSX ONTAP 支援以客為本的連線儲存設備
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* FSX ONTAP 支援原生資料存放區：1^


檢視詳細資訊 link:aws/aws-guest.html["VMC的來賓連線儲存選項"]。

檢視詳細資訊 link:aws-guest.html["VMC的來賓連線儲存選項"]。


NOTE: 1 - VMC的FSxN目前位於IA（初始可用度）。如需詳細資訊、請聯絡您的NetApp銷售代表。

--
.Azure / AVS
--
Azure以下列組態支援NetApp儲存設備：

* 以客體連線儲存設備的形式提供Azure NetApp Files
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* 以原生資料存放區形式提供的資料（ANF）Azure NetApp Files


檢視詳細資訊 link:azure/azure-guest.html["AVS的來賓連線儲存選項"]。

檢視詳細資訊 link:azure-guest.html["AVS的來賓連線儲存選項"]。


NOTE: 1 - ANF做為AVS的原生資料存放區目前位於Public Preview中。深入瞭解 https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["請按這裡"]。

--
.GCP / GCV
--
Google Cloud支援下列組態的NetApp儲存設備：

* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* 以客體連線儲存設備的形式提供資訊（CVS）Cloud Volumes Service
* 以原生資料存放區形式提供的支援（CVS）Cloud Volumes Service


檢視詳細資訊 link:gcp/gcp-guest.html["GCVE的來賓連線儲存選項"]。

檢視詳細資訊 link:gcp-guest.html["GCVE的來賓連線儲存選項"]。

深入瞭解 link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["以原生資料存放區形式提供的支援（CVS）Cloud Volumes Service"^]。


NOTE: 1 -目前處於私有預覽中

--
====