= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS支援下列組態的NetApp儲存設備：

* FSX ONTAP 支援以客為本的連線儲存設備
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* FSX ONTAP 不只是NFS的補充資料存放區


檢視詳細資訊 link:aws-guest.html["VMC的來賓連線儲存選項"]。檢視詳細資訊 link:aws-native-nfs-datastore-option.html["VMC的補充NFS資料存放區選項"]。

檢視詳細資訊 link:aws-guest.html["VMC的來賓連線儲存選項"]。檢視詳細資訊 link:aws-native-nfs-datastore-option.html["VMC的補充NFS資料存放區選項"]。

--
.Azure / AVS
--
Azure以下列組態支援NetApp儲存設備：

* 以客體連線儲存設備的形式提供Azure NetApp Files
* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* 作爲NFS補充資料存放區的能力（ANF Azure NetApp Files ）


檢視詳細資訊 link:azure-guest.html["AVS的來賓連線儲存選項"]。檢視詳細資訊 link:azure-native-nfs-datastore-option.html["AVS的補充NFS資料存放區選項"]。

檢視詳細資訊 link:azure-guest.html["AVS的來賓連線儲存選項"]。檢視詳細資訊 link:azure-native-nfs-datastore-option.html["AVS的補充NFS資料存放區選項"]。

--
.GCP / GCV
--
Google Cloud支援下列組態的NetApp儲存設備：

* 以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP
* 以客體連線儲存設備的形式提供資訊（CVS）Cloud Volumes Service
* 作爲NFS補充資料存放區的CVS Cloud Volumes Service


檢視詳細資訊 link:gcp-guest.html["GCVE的來賓連線儲存選項"]。

檢視詳細資訊 link:gcp-guest.html["GCVE的來賓連線儲存選項"]。

深入瞭解 link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["NetApp Cloud Volumes Service 支援Google Cloud VMware Engine的資料儲存區（NetApp部落格）"^] 或 link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["如何使用NetApp CVS做為Google Cloud VMware Engine的資料存放區（Google部落格）"^]

--
====