---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_migration.html 
summary: 本節詳細說明將Oracle資料庫從內部部署移轉至AWS EC2執行個體和FSX儲存設備時、應考慮的因素。 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= 資料庫從內部部署移轉至公有雲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:aws_ora_fsx_ec2_mgmt.html["上一篇：資料庫管理。"]

[role="lead"]
資料庫移轉是一項艱鉅的工作、無論以何種方式進行。將Oracle資料庫從內部部署移轉至雲端也不例外。

下列各節提供將Oracle資料庫移轉至AWS公有雲時、使用AWS EC2運算和FSX儲存平台時、必須考量的關鍵因素。



== 內部部署可儲存資料ONTAP

如果內部部署的Oracle資料庫位於ONTAP 某個不支援的儲存陣列上、那麼使用內建於AWS FSX ONTAP S庫 的NetApp SnapMirror技術、就能更輕鬆地設定資料庫移轉的複寫作業。您可以使用NetApp BlueXP主控台來協調移轉程序。

. 建置符合內部部署執行個體的目標運算EC2執行個體。
. 從FSX主控台配置大小相同的相符資料庫Volume。
. 將FSX資料庫磁碟區掛載到EC2執行個體。
. 在內部部署資料庫磁碟區之間、設定SnapMirror複寫至目標FSX資料庫磁碟區。初始同步可能需要一些時間來移動主要來源資料、但後續的任何遞增更新都會更快。
. 切換時、請關閉主要應用程式以停止所有交易。在Oracle sqlplus CLI介面中、執行Oracle線上記錄交換器、並允許SnapMirror同步將上次歸檔的記錄推送至目標磁碟區。
. 中斷鏡射磁碟區、在目標執行Oracle恢復、並啟動資料庫以供服務。
. 將應用程式指向雲端中的Oracle資料庫。


下列影片示範如何使用NetApp BlueXP主控台和SnapMirror複寫、將Oracle資料庫從內部部署移轉至AWS FSx/EC2。

video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto,width=360]


== 內部不提供儲存功能ONTAP

如果內部部署的Oracle資料庫裝載於ONTAP 非Oracle以外的協力廠商儲存設備、則資料庫移轉將以還原Oracle資料庫備份複本為基礎。切換前、您必須先播放歸檔記錄檔以使其保持最新狀態。

AWS S3可做為移轉儲存區域、用於資料庫移動和移轉。請參閱下列詳細步驟以瞭解此方法：

. 提供與內部部署執行個體類似的新EC2執行個體。
. 從FSX儲存設備配置等量的資料庫磁碟區、然後將磁碟區掛載至EC2執行個體。
. 建立磁碟層級的Oracle備份複本。
. 將備份複本移至AWS S3儲存設備。
. 重新建立Oracle控制檔、並從S3儲存設備提取資料和歸檔記錄、以還原及恢復資料庫。
. 將目標Oracle資料庫與內部部署來源資料庫同步。
. 切換時、請關閉應用程式和來源Oracle資料庫。複製最後幾個歸檔記錄、並將其套用至目標Oracle資料庫、使其保持最新狀態。
. 啟動目標資料庫以供使用者存取。
. 將應用程式重新導向至目標資料庫以完成切換。




== 使用最大可用度的pdb重新配置、將內部部署的Oracle資料庫移轉至AWS FSx/EC2

這種移轉方法最適合已部署於PDB/CDB多租戶模式的Oracle資料庫、ONTAP 而且無法在內部部署使用此功能。pdb重新配置方法使用Oracle pdb熱複製技術、在來源CDB和目標CDB之間移動PDB、同時將服務中斷降至最低。

首先、請在AWS FSx/EC2中建立CDB、並提供足夠的儲存空間來裝載要從內部部署移轉的PDF。多個內部部署的PDF可一次移轉一個。

. 如果內部部署資料庫是部署在單一執行個體中、而非部署在多租戶PDB/CDB模式中、請依照中的指示進行 link:https://docs.netapp.com/us-en/netapp-solutions/databases/azure_ora_nfile_migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["將單一非CDB執行個體轉換為多租戶CDB中的pdb"^] 將單一執行個體轉換為多租戶PDB/CDB。然後依照下一個步驟、將轉換後的pdb移轉至AWS FSx/EC2中的CDB。
. 如果已在多租戶PDB/CDB模式中部署內部部署資料庫、請依照中的指示進行 link:https://docs.netapp.com/us-en/netapp-solutions/databases/azure_ora_nfile_migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["透過重新配置pdb、將內部部署的Oracle資料庫移轉至雲端"^] 以執行移轉。


下列影片示範如何使用最大可用度的pdb重新配置、將Oracle資料庫（pdb）移轉至FSx/EC2。

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["將內部部署的Oracle pdb移轉至具備最大可用度的AWS CDB"^]


NOTE: 雖然步驟1和步驟2中的指示已在Azure公有雲的背景中說明、但這些程序適用於AWS雲端、不會有任何變更。

NetApp解決方案自動化團隊提供移轉工具套件、可協助Oracle資料庫從內部部署移轉至AWS雲端。使用下列命令下載適用於重新配置pdb的Oracle資料庫移轉工具套件。

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----