---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_deploy_intro.html 
summary: 本白皮書概述並驗證AWS自訂的Oracle RDS資料庫HA和DR解決方案、並在多重可用度區域部署中運用AWS FSX儲存服務。 
keywords: HA, DR, database, Oracle, RDS, AWS 
---
= WP-7357：EC2上的Oracle資料庫部署與FSX最佳實務做法簡介
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


NetApp公司的Alleno Cao、Niyazz Mohamed, Jeffrey Steiner

[role="lead"]
許多任務關鍵型企業Oracle資料庫仍在內部部署、許多企業正尋求將這些Oracle資料庫移轉至公有雲。這些Oracle資料庫通常以應用程式為中心、因此需要使用者專屬的組態、這是許多資料庫即服務公有雲產品無法提供的功能。因此、目前的資料庫環境需要以公有雲為基礎的Oracle資料庫解決方案、此解決方案是以高效能、可擴充的運算與儲存服務所打造、能夠滿足獨特的需求。AWS EC2運算執行個體和AWS FSX儲存服務可能是這個難題的一部分、您可以利用這些難題來建置任務關鍵型Oracle資料庫工作負載、並將其移轉至公有雲。

Amazon Elastic Compute Cloud（Amazon EC2）是一項網路服務、可在雲端中提供安全、可調整大小的運算容量。其設計旨在讓企業更輕鬆地進行網路規模的雲端運算。簡單的Amazon EC2網路服務介面可讓您以最少的摩擦取得及設定容量。它可讓您完全掌控運算資源、並讓您在Amazon備受肯定的運算環境中執行。

Amazon FSX ONTAP 是 AWS 儲存服務、使用領先業界的 NetApp ONTAP 區塊和檔案儲存設備、可公開 NFS 、 SMB 和 iSCSI 。有了如此強大的儲存引擎、將關鍵任務Oracle資料庫應用程式重新部署到AWS的工作變得前所未有的輕鬆、每個資料庫執行個體的回應時間低於毫秒、處理量高達多Gbps、IOPS超過10萬次。更棒的是、FSX儲存服務具備原生複寫功能、可讓您輕鬆將內部部署的Oracle資料庫移轉至AWS、或將關鍵任務Oracle資料庫複寫至次要AWS可用性區域、以供HA或DR使用。

本文件的目標是提供逐步程序、程序和最佳實務做法指引、說明如何部署及設定具有FSX儲存設備的Oracle資料庫、以及提供與內部部署系統類似效能的EC2執行個體。NetApp也提供自動化工具套件、可將部署、組態及管理AWS公有雲中Oracle資料庫工作負載所需的大部分工作自動化。

若要深入瞭解解決方案和使用案例、請觀看以下總覽影片：

link:https://www.netapp.tv/insight/details/30000?playlist_id=275&mcid=04891225598830484314259903524057913910["利用AWS和FSX ONTAP 功能的混合雲將Oracle資料庫現代化、第1部分：使用案例和解決方案架構"^]
