---
sidebar: sidebar 
permalink: databases/awx_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 本頁說明將Oracle19c部署在NetApp ONTAP 內存上的自動化方法。 
---
= 逐步部署程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== AWX/Tower部署Oracle 19c資料庫



=== 1.為您的環境建立詳細目錄、群組、主機和認證資料

本節說明在AWX/Ansible Tower中設定庫存、群組、主機和存取認證資料、為使用NetApp自動化解決方案的環境做好準備。

. 設定庫存。
+
.. 瀏覽至「資源」→「庫存」→「新增」、然後按一下「新增庫存」。
.. 提供名稱和組織詳細資料、然後按一下「Save（儲存）」。
.. 在「庫存」頁面上、按一下建立的庫存。
.. 如果有任何庫存變數、請將其貼到變數欄位中。
.. 瀏覽至「群組」子功能表、然後按一下「新增」。
.. 提供ONTAP 群組名稱以供使用、貼上群組變數（若有）、然後按一下「Save（儲存）」。
.. 為Oracle的另一個群組重複此程序。
.. 選取ONTAP 建立的「更新群組」、移至「主機」子功能表、然後按一下「新增主機」。
.. 提供ONTAP 叢集管理IP的IP位址、貼上主機變數（如果有）、然後按一下「Save（儲存）」。
.. Oracle群組和Oracle主機管理IP/主機名稱必須重複此程序。


. 建立認證類型。對於涉及ONTAP 到靜態的解決方案、您必須設定認證類型以符合使用者名稱和密碼項目。
+
.. 瀏覽至「管理」→「認證類型」、然後按一下「新增」。
.. 提供名稱和說明。
.. 在輸入組態中貼上下列內容：
+
[source, cli]
----
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
  - id: vsadmin_password
    type: string
    label: vsadmin_password
    secret: true
----
.. 將下列內容貼到Injector Configuration：
+
[source, cli]
----
extra_vars:
  password: '{{ password }}'
  username: '{{ username }}'
  vsadmin_password: '{{ vsadmin_password }}'
----


. 設定認證資料。
+
.. 瀏覽至「資源」→「認證」、然後按一下「新增」。
.. 輸入ONTAP 名稱和組織詳細資料以供參考。
.. 選取您為ONTAP 其建立的自訂認證類型。
.. 在類型詳細資料下、輸入使用者名稱、密碼和vsadmin_password。
.. 按一下「Back to Credential（返回認證）」、然後按
.. 輸入Oracle的名稱和組織詳細資料。
.. 選取機器認證類型。
.. 在類型詳細資料下、輸入Oracle主機的使用者名稱和密碼。
.. 選取正確的權限提高方法、然後輸入使用者名稱和密碼。






=== 2.建立專案

. 前往「資源」→「專案」、然後按一下「新增」。
+
.. 輸入名稱和組織詳細資料。
.. 在來源控制認證類型欄位中選取Git。
.. 輸入 <https://[] 做為來源控制URL。
.. 按一下儲存。
.. 當來源程式碼變更時、專案可能需要偶爾同步。






=== 3.設定Oracle host_vars

本節中定義的變數會套用至每個個別的Oracle伺服器和資料庫。

. 在下列內嵌的Oracle主機變數或host_vars表單中輸入您的環境特定參數。



NOTE: 必須變更藍色項目、以符合您的環境。



=== 主機VARS組態


. 填寫藍色欄位中的所有變數。
. 完成變數輸入後、按一下表單上的「複製」按鈕、將所有變數複製到AWX或Tower。
. 瀏覽至AWX或Tower、前往「Resources（資源）」→「hosts（主機）」、然後選取並開啟Oracle伺服器組態頁面。
. 在「詳細資料」索引標籤下、按一下「編輯」、然後將步驟1中的複製變數貼到「Yaml」索引標籤下的「變數」欄位。
. 按一下儲存。
. 對系統中的任何其他Oracle伺服器重複此程序。




=== 4.設定全域變數

本節中定義的變數適用於所有Oracle主機、資料庫和ONTAP 叢集。

. 在下列內嵌的整體變數或vars表單中輸入您的環境特定參數。
+

NOTE: 必須變更藍色項目、以符合您的環境。





=== VAR


. 在藍色欄位中填入所有變數。
. 完成變數輸入後、按一下表單上的「複製」按鈕、將所有要傳輸到AWX或Tower的變數複製到下列工作範本。




=== 5.設定及啟動工作範本。

. 建立工作範本。
+
.. 瀏覽至「資源」→「範本」→「新增」、然後按一下「新增工作範本」
.. 輸入名稱和說明
.. 選取工作類型；執行會根據方針來設定系統、而檢查會執行方針檔的乾式執行、而不會實際設定系統。
.. 選取相應的資源清冊、專案、方針及方針認證、以供教戰手冊使用。
.. 選取all_playbook。yml作為要執行的預設教戰手冊。
.. 將從步驟4複製的全域變數貼到Yaml索引標籤下的「範本變數」欄位。
.. 核取「工作標籤」欄位中的「啟動時提示」方塊。
.. 按一下儲存。


. 啟動工作範本。
+
.. 瀏覽至資源→範本。
.. 按一下所需的範本、然後按一下啟動。
.. 當系統在啟動時提示您輸入「工作標籤」時、請輸入「Requirements _config」。您可能需要按一下「Requirements _config」下方的「Create Job Tag（建立工作標籤）」行、以輸入工作標籤。
+

NOTE: Requirements _config可確保您擁有正確的程式庫來執行其他角色。

.. 按一下「Next（下一步）」、然後按「Launch（啟動）」開始工作
.. 按一下「檢視」→「工作」以監控工作輸出和進度。
.. 當系統在啟動時提示您輸入「工作標籤」時、請輸入ONTAP_config。您可能需要按一下ONTAP_config下方的「Create "Job Tag"（建立「工作標籤」）行、以輸入工作標籤。
.. 按一下「Next（下一步）」、然後按「Launch（啟動）」開始工作
.. 按一下「檢視」→「工作」以監控工作輸出和進度
.. 在ONTAP_config角色完成後、再次執行Linux組態的程序。
.. 瀏覽至資源→範本。
.. 選取所需的範本、然後按一下「啟動」。
.. 在Linux組態中、當系統在啟動時提示您輸入「工作標籤」類型時、您可能需要選取Linux組態下方的「建立工作標籤」行、以輸入工作標籤。
.. 按一下「Next（下一步）」、然後按「Launch（啟動）」開始工作
.. 選取「檢視」→「工作」以監控工作輸出和進度。
.. Linux組態角色完成後、請再次執行Oracle_config的程序。
.. 前往資源→範本。
.. 選取所需的範本、然後按一下「啟動」。
.. 當系統在啟動時提示您輸入「工作標籤」時、請輸入oracle_config。您可能需要選取Oracle_config下方的「Create "Job Tag"（建立「工作標籤」）行、以輸入工作標籤。
.. 按一下「Next（下一步）」、然後按「Launch（啟動）」開始工作
.. 選取「檢視」→「工作」以監控工作輸出和進度。






=== 6.在相同的Oracle主機上部署額外的資料庫

每次執行時、實戰手冊的Oracle部分會在Oracle伺服器上建立單一Oracle Container資料庫。若要在同一部伺服器上建立其他容器資料庫、請完成下列步驟。

. 修改host_var變數。
+
.. 返回步驟2：設定Oracle host_vars。
.. 將Oracle SID變更為不同的命名字串。
.. 將接聽程式連接埠變更為不同的號碼。
.. 如果您要安裝EM Express、請將EM Express連接埠變更為不同的編號。
.. 將修訂的主機變數複製並貼到「主機組態詳細資料」索引標籤的「Oracle主機變數」欄位。


. 僅使用oracle_config標記啟動部署工作範本。




=== 驗證Oracle安裝


[source, cli]
----
ps -ef | grep ora
----

NOTE: 如果安裝已如預期完成、且Oracle資料庫已啟動、則會列出Oracle程序


[source, cli]
----
sqlplus / as sysdba
----
[Oracle@localhost ~]$ sqlplus / AS Sysdba

SQL* Plus：19.0．0．0．0版- 5月6日（星期四）上線：12：52：51 2021版本19.8．0．0

Copyright（c）1982,2019、Oracle。版權所有。

連線至：Oracle Database 19c Enterprise Edition 19.0.00.0版-正式作業版本19.8.0.0.0

SQL>

[source, cli]
----
select name, log_mode from v$database;
----
SQL>從v$database_mode中選擇名稱、log_mode；名稱log_mode －－－－－－－ CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
SQL>顯示PDF

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
SQL> col svrname form A30 SQL> col dirname form A30 SQL>從v$dnfs_servers中選取svrname、dirname、nfsversion；

SVRNAME目錄NFSVERSion －－－－－－－－－－－－－－－ －－－－－－－ 172.21.126.200 /rhelora03_u02 NFSv3.0 172.21.126.200 /rhelora03_u03 NFSv3.0 172.21.126.200 /rhelora03_u01 NFSv3.0

[listing]
----
This confirms that dNFS is working properly.
----

[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[Oracle@localhost ~]$ sqlplus system@//localhost:1523/ cdb2_pdb1.cie.netapp.com

SQL* Plus：19.0．0．0．0版- 5月6日星期四正式上線13：19：57 2021版本19.8．0．0

Copyright（c）1982,2019、Oracle。版權所有。

輸入密碼：上次成功登入時間：2021年5月3日下午5：11：11 - 04：00

連線至：Oracle Database 19c Enterprise Edition 19.0.00.0版-正式作業版本19.8.0.0.0

SQL>顯示使用者為「system" SQL>顯示con_name con_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== 哪裡可以取得協助？

如果您需要工具組的協助、請加入 link:https://netapppub.slack.com/archives/C021R4WC0LC["NetApp解決方案自動化社群支援閒散通道"] 並尋找解決方案自動化通路、以張貼您的問題或詢問。
