---
sidebar: sidebar 
permalink: databases/cli_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 本頁說明將Oracle19c部署在NetApp ONTAP 內存上的自動化方法。 
---
= 逐步部署程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本文件詳細說明如何使用自動化命令列介面（ CLI ）部署 Oracle 19c 。



== CLI部署Oracle 19c資料庫

本節說明使用CLI準備及部署Oracle19c資料庫所需的步驟。請確定您已檢閱 link:getting_started_requirements.html["「使用入門與需求」一節"] 並據此準備環境。



=== 下載Oracle19c repo

. 從 Ansible 控制器執行下列命令：


[source, cli]
----
git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git
----
. 下載儲存庫之後、請將目錄變更為 na_oracle19c_deploy <cd na_oracle19c_deploy> 。




=== 編輯hosts檔案

部署前請先完成下列事項：

. 編輯主機檔案na_oracle19c_deploy目錄。
. 在[ESI]下ONTAP 、將IP位址變更為叢集管理IP。
. 在[Oracle]群組下、新增Oracle主機名稱。主機名稱必須透過DNS或主機檔案解析為其IP位址、或必須在主機中指定。
. 完成這些步驟之後、請儲存任何變更。


以下範例說明主機檔案：

[source, shell]
----
#ONTAP Host

[ontap]

"10.61.184.183"

#Oracle hosts

[oracle]

"rtpora01"

"rtpora02"
----
此範例執行方針、並在兩部Oracle資料庫伺服器上同時部署Oracle 19c。您也可以只用一部資料庫伺服器進行測試。在這種情況下、您只需要設定一個主機變數檔案。


NOTE: 無論您部署多少Oracle主機和資料庫、實戰手冊的執行方式都相同。



=== 在host_vars下編輯host_name.yml檔案

每個Oracle主機的主機變數檔案都會以主機名稱識別、其中包含主機專屬的變數。您可以為主機指定任何名稱。編輯並複製「Host VARS Config（主機VARS組態）」區段中的「host_vars」、然後貼到您想要的「host_name.yml」檔案中。


NOTE: 必須變更藍色項目、以符合您的環境。



=== 主機VARS組態

[source, shell]
----
######################################################################
##############      Host Variables Configuration        ##############
######################################################################

# Add your Oracle Host
ansible_host: "10.61.180.15"

# Oracle db log archive mode: true - ARCHIVELOG or false - NOARCHIVELOG
log_archive_mode: "true"

# Number of pluggable databases per container instance identified by sid. Pdb_name specifies the prefix for container database naming in this case cdb2_pdb1, cdb2_pdb2, cdb2_pdb3
oracle_sid: "cdb2"
pdb_num: "3"
pdb_name: "{{ oracle_sid }}_pdb"

# CDB listener port, use different listener port for additional CDB on same host
listener_port: "1523"

# CDB is created with SGA at 75% of memory_limit, MB. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB. The grand total SGA should not exceed 75% available RAM on node.
memory_limit: "5464"

# Set "em_configuration: DBEXPRESS" to install enterprise manager express and choose a unique port from 5500 to 5599 for each sid on the host.
# Leave them black if em express is not installed.
em_configuration: "DBEXPRESS"
em_express_port: "5501"

# {{groups.oracle[0]}} represents first Oracle DB server as defined in Oracle hosts group [oracle]. For concurrent multiple Oracle DB servers deployment, [0] will be incremented for each additional DB server. For example,  {{groups.oracle[1]}}" represents DB server 2, "{{groups.oracle[2]}}" represents DB server 3 ... As a good practice and the default, minimum three volumes is allocated to a DB server with corresponding /u01, /u02, /u03 mount points, which store oracle binary, oracle data, and oracle recovery files respectively. Additional volumes can be added by click on "More NFS volumes" but the number of volumes allocated to a DB server must match with what is defined in global vars file by volumes_nfs parameter, which dictates how many volumes are to be created for each DB server.
host_datastores_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
----


=== 編輯vars.yml檔案

vars.yml檔案整合了ONTAP 所有環境特定的變數（例如、Linux或Oracle）、以供Oracle部署。

* 編輯並複製VARS區段中的變數、然後將這些變數貼到您的「vars.yml」檔案中。


[source, shell]
----
#######################################################################
###### Oracle 19c deployment global user configuration variables ######
######  Consolidate all variables from ontap, linux and oracle   ######
#######################################################################

###########################################
### Ontap env specific config variables ###
###########################################

#Inventory group name
#Default inventory group name - 'ontap'
#Change only if you are changing the group name either in inventory/hosts file or in inventory groups in case of AWX/Tower
hosts_group: "ontap"

#CA_signed_certificates (ONLY CHANGE to 'true' IF YOU ARE USING CA SIGNED CERTIFICATES)
ca_signed_certs: "false"

#Names of the Nodes in the ONTAP Cluster
nodes:
 - "AFF-01"
 - "AFF-02"


#Storage VLANs
#Add additional rows for vlans as necessary
storage_vlans:
   - {vlan_id: "203", name: "infra_NFS", protocol: "NFS"}
More Storage VLANsEnter Storage VLANs details

#Details of the Data Aggregates that need to be created
#If Aggregate creation takes longer, subsequent tasks of creating volumes may fail.
#There should be enough disks already zeroed in the cluster, otherwise aggregate create will zero the disks and will take long time
data_aggregates:
  - {aggr_name: "aggr01_node01"}
  - {aggr_name: "aggr01_node02"}

#SVM name
svm_name: "ora_svm"


# SVM Management LIF Details
svm_mgmt_details:
  - {address: "172.21.91.100", netmask: "255.255.255.0", home_port: "e0M"}

# NFS storage parameters when data_protocol set to NFS. Volume named after Oracle hosts name identified by mount point as follow for oracle DB server 1. Each mount point dedicates to a particular Oracle files: u01 - Oracle binary, u02 - Oracle data, u03 - Oracle redo. Add additional volumes by click on "More NFS volumes" and also add the volumes list to corresponding host_vars as host_datastores_nfs variable. For multiple DB server deployment, additional volumes sets needs to be added for additional DB server. Input variable "{{groups.oracle[1]}}_u01", "{{groups.oracle[1]}}_u02", and "{{groups.oracle[1]}}_u03" as vol_name for second DB server. Place volumes for multiple DB servers alternatingly between controllers for balanced IO performance, e.g. DB server 1 on controller node1, DB server 2 on controller node2 etc. Make sure match lif address with controller node.
volumes_nfs:
  - {vol_name: "{{groups.oracle[0]}}_u01", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u02", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}
  - {vol_name: "{{groups.oracle[0]}}_u03", aggr_name: "aggr01_node01", lif: "172.21.94.200", size: "25"}

#NFS LIFs IP address and netmask
nfs_lifs_details:
  - address: "172.21.94.200" #for node-1
    netmask: "255.255.255.0"
  - address: "172.21.94.201" #for node-2
    netmask: "255.255.255.0"

#NFS client match
client_match: "172.21.94.0/24"

###########################################
### Linux env specific config variables ###
###########################################

#NFS Mount points for Oracle DB volumes
mount_points:
  - "/u01"
  - "/u02"
  - "/u03"

# Up to 75% of node memory size divided by 2mb. Consider how many databases to be hosted on the node and how much ram to be allocated to each DB.
# Leave it blank if hugepage is not configured on the host.
hugepages_nr: "1234"

# RedHat subscription username and password
redhat_sub_username: "xxx"
redhat_sub_password: "xxx"

####################################################
### DB env specific install and config variables ###
####################################################

db_domain: "your.domain.com"

# Set initial password for all required Oracle passwords. Change them after installation.
initial_pwd_all: "netapp123"
----


=== 執行教戰手冊

在完成必要的環境先決條件、並將變數複製到「vars.yml」和「yer_host.yml」之後、您就可以開始部署教戰手冊了。


NOTE: 必須變更以符合您的環境。

. 傳送正確的標記和 ONTAP 叢集使用者名稱、以執行 ONTAP 教戰手冊。請填入 ONTAP 叢集的密碼、並在系統提示時填入 vsadmin 。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml
----
. 執行 Linux 教戰手冊以執行部署的 Linux 部分。輸入管理 ssh 密碼和 Sudo 密碼。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml
----
. 執行 Oracle 教戰手冊以執行部署的 Oracle 部分。輸入管理 ssh 密碼和 Sudo 密碼。


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml
----


=== 在相同的Oracle主機上部署額外的資料庫

每次執行時、實戰手冊的Oracle部分會在Oracle伺服器上建立單一Oracle Container資料庫。若要在同一部伺服器上建立其他容器資料庫、請完成下列步驟：

. 修改host_vars變數。
+
.. 返回步驟3 -在「host_vars」下編輯「host_name.yml」檔案。
.. 將Oracle SID變更為不同的命名字串。
.. 將接聽程式連接埠變更為不同的號碼。
.. 如果您已安裝EM Express、請將EM Express連接埠變更為不同的編號。
.. 將修訂的主機變數複製並貼到Oracle主機變數檔案的「host_vars」下。


. 執行含有「oracle_config」標記的方針、如上所示 <<執行教戰手冊>>。




=== 驗證Oracle安裝

. 以 Oracle 使用者身分登入 Oracle 伺服器、然後執行下列命令：


[source, cli]
----
ps -ef | grep ora
----

NOTE: 如果安裝已如預期完成、且Oracle資料庫已啟動、則會列出Oracle程序

. 登入資料庫、檢查使用下列命令集建立的資料庫組態設定和 PDB 。


[source, cli]
----
sqlplus / as sysdba
----
[Oracle@localhost ~]$ sqlplus / AS Sysdba

SQL* Plus：19.0．0．0．0版- 5月6日（星期四）上線：12：52：51 2021版本19.8．0．0

Copyright（c）1982,2019、Oracle。版權所有。

連線至：Oracle Database 19c Enterprise Edition 19.0.00.0版-正式作業版本19.8.0.0.0

SQL>

[source, cli]
----
select name, log_mode from v$database;
----
SQL>從v$database_mode中選擇名稱、log_mode；名稱log_mode －－－－－－－ CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
SQL>顯示PDF

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
SQL> col svrname form A30 SQL> col dirname form A30 SQL>從v$dnfs_servers中選取svrname、dirname、nfsversion；

SVRNAME目錄NFSVERSion －－－－－－－－－－－－－－－ －－－－－－－ 172.21.126.200 /rhelora03_u02 NFSv3.0 172.21.126.200 /rhelora03_u03 NFSv3.0 172.21.126.200 /rhelora03_u01 NFSv3.0

[listing]
----
This confirms that dNFS is working properly.
----
. 透過接聽程式連線至資料庫、使用下列命令檢查 hte Oracle 接聽程式組態。變更為適當的接聽程式連接埠和資料庫服務名稱。


[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[Oracle@localhost ~]$ sqlplus system@//localhost:1523/ cdb2_pdb1.cie.netapp.com

SQL* Plus：19.0．0．0．0版- 5月6日星期四正式上線13：19：57 2021版本19.8．0．0

Copyright（c）1982,2019、Oracle。版權所有。

輸入密碼：上次成功登入時間：2021年5月3日下午5：11：11 - 04：00

連線至：Oracle Database 19c Enterprise Edition 19.0.00.0版-正式作業版本19.8.0.0.0

SQL>顯示使用者為「system" SQL>顯示con_name con_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== 哪裡可以取得協助？

如果您需要工具組的協助、請加入 link:https://netapppub.slack.com/archives/C021R4WC0LC["NetApp解決方案自動化社群支援閒散通道"] 並尋找解決方案自動化通路、以張貼您的問題或詢問。
