---
sidebar: sidebar 
permalink: databases/db_protection_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 本頁說明將Oracle19c部署在NetApp ONTAP 內存上的自動化方法。 
---
= 解決方案總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Oracle資料庫的自動化資料保護

組織正在將環境自動化、以提高效率、加速部署、並減少手動作業。Ansible等組態管理工具正用於簡化企業資料庫作業。在本解決方案中、我們將示範如何使用Ansible來自動化Oracle with NetApp ONTAP 的資料保護。藉由讓儲存管理員、系統管理員及DBA能夠一致且快速地設定資料複寫至異地資料中心或公有雲、您將獲得下列效益：

* 消除設計複雜性和人為錯誤、並實作可重複執行的一致部署和最佳實務做法
* 縮短叢集間複寫、CVO具現化及Oracle資料庫恢復的設定時間
* 提高資料庫管理員、系統和儲存管理員的生產力
* 提供資料庫還原工作流程、以便輕鬆測試災難恢復案例。


NetApp為客戶提供通過驗證的Ansible模組和角色、以加速Oracle資料庫環境的部署、組態和生命週期管理。本解決方案提供說明及可接受的方針代碼、協助您：



=== 在Prem到on prem複寫上

* 在來源與目的地上建立叢集間生命體
* 建立叢集與Vserver對等關係
* 建立並初始化Oracle Volume的SnapMirror
* 透過AWX/Tower建立Oracle二進位檔、資料庫和記錄的複寫排程
* 在目的地上還原Oracle資料庫、並使資料庫上線




=== 在AWS的Prem到CVO上

* 建立AWS連接器
* 在AWS中建立CVO執行個體
* 將內部部署的叢集新增至Cloud Manager
* 在來源上建立叢集間LIF
* 建立叢集與Vserver對等關係
* 建立並初始化Oracle Volume的SnapMirror
* 透過AWX/Tower建立Oracle二進位檔、資料庫和記錄的複寫排程
* 在目的地上還原Oracle資料庫、並使資料庫上線


如需更多詳細資料或要開始、請參閱下方的總覽影片。



=== AWX/Tower部署

* 第1部分：待定
+
影片::


* 第2部分：待定
+
影片:: 準備好之後、按一下 link:db_protection_getting_started.html["請參閱此處以瞭解解決方案的使用入門"]。



