---
sidebar: sidebar 
permalink: databases/getting_started_requirements.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 本頁說明將Oracle19c部署在NetApp ONTAP 內存上的自動化方法。 
---
= 快速入門
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本解決方案的設計可在AWX/Tower環境中執行、或由CLI在Ansible控制主機上執行。



== AWX/Tower

對於AWX/Tower環境、我們會引導您建立ONTAP 一份關於您的叢集管理和Oracle伺服器（IP和主機名稱）的目錄、建立認證資料、設定從NetApp Automation Github擷取Ansible程式碼的專案、以及啟動自動化的工作範本。

. 填寫環境專屬的變數、然後複製並貼到工作範本中的額外VAR欄位。
. 將額外的虛擬檔案新增至工作範本之後、您就可以啟動自動化。
. 工作範本會在三個階段中執行、分別為ONTAP_config、Linux組態和Oracle_config指定標籤。




== 透過Ansible控制主機的CLI

. 可設定Linux主機、以便用作可控制主機link:../automation/getting-started.html["請按一下此處以取得詳細指示"]
. 設定好Ansible控制主機之後、您可以複製Ansible Automation儲存庫。
. 使用ONTAP 您的叢集管理和Oracle伺服器管理IP的IP和/或主機名稱編輯hosts檔案。
. 填寫您環境的專屬變數、然後複製並貼到「vars.yml」檔案中。
. 每個Oracle主機都有一個變數檔、由其主機名稱識別、其中包含主機專屬的變數。
. 完成所有變數檔案之後、您可以指定「ONTAP_config」、「LINUS_config」和「Oracle_config」的標記、以三個階段執行方針。




== 需求

[cols="3, 9"]
|===
| 環境 | 需求 


.4+| *可環境* | 將AWX/Tower或Linux主機當作可控制主機 


| Ansible v.不 包括更新版本 


| Python 3. 


| Python程式庫- NetApp-Lib - xmltodict - jmespath 


.3+| *《*》ONTAP | 版本9.3 - ONTAP 9.7 


| 兩個資料集合體 


| NFS VLAN和ifgrp已建立 


.5+| * Oracle伺服器* | RHEL 7/8 


| Oracle Linux 7/8 


| 網路介面、適用於NFS、公有及選用的管理 


| Oracle伺服器上的Oracle安裝檔案 
|===


== 自動化詳細資料

這項自動化部署是以單一的可執行教戰手冊所設計、其中包含三個不同的角色。這些角色適用於ONTAP 支援功能、Linux和Oracle組態。下表說明哪些工作正在自動化。

[cols="4, 9"]
|===
| 角色 | 工作 


.5+| * ONTAP組態* | 預先檢查ONTAP 整個環境 


| 為Oracle建立NFS型SVM 


| 建立匯出原則 


| 為Oracle建立磁碟區 


| 建立NFS LIF 


.9+| * Linux組態* | 建立掛載點並掛載NFS磁碟區 


| 驗證NFS裝載 


| 作業系統專屬組態 


| 建立Oracle目錄 


| 設定Hugepages 


| 停用SELinux和防火牆精靈 


| 啟用並啟動同步服務 


| 增加檔案描述元硬限制 


| 建立pam．d工作階段檔案 


.8+| * Oracle_config* | Oracle軟體安裝 


| 建立Oracle接聽程式 


| 建立Oracle資料庫 


| Oracle環境組態 


| 儲存pdb狀態 


| 啟用執行個體歸檔模式 


| 啟用DNFS用戶端 


| 在作業系統重新開機期間啟用資料庫自動開機和關機 
|===


== 預設參數

為了簡化自動化作業、我們預設了許多必要的Oracle部署參數、預設值為預設值。一般而言、大多數部署都不需要變更預設參數。較進階的使用者可以謹慎變更預設參數。預設參數位於預設目錄下的每個角色資料夾中。



== 部署指示

在開始之前、請先下載下列Oracle安裝與修補檔案、並將其放在「/tmp/archive」目錄中、並針對要部署的每部DB伺服器上的所有使用者、提供讀取、寫入及執行存取權限。自動化工作會在該特定目錄中尋找命名的安裝檔案、以供Oracle安裝與組態之用。

[listing]
----
LINUX.X64_193000_db_home.zip -- 19.3 base installer
p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23
----


== 授權

您應該閱讀Github儲存庫中所述的授權資訊。存取、下載、安裝或使用此儲存庫中的內容、即表示您同意所規定的授權條款 link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["請按這裡"^]。

請注意、對於產生及/或分享任何衍生作品與此儲存庫中的內容有特定限制。請務必閱讀的條款 link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["授權"^] 使用內容之前。如果您不同意所有條款、請勿存取、下載或使用此儲存庫中的內容。

準備好之後、按一下 link:awx_automation.html["如需詳細的AWX/Tower部署程序、請參閱此處"] 或 link:cli_automation.html["此處用於CLI部署"]。
