---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prereq_cloud.html 
summary: 在安裝Cloud Manager連接器及Cloud Volumes ONTAP 進行SnapMirror的不中斷和設定之前、我們必須先為雲端環境做一些準備。本頁說明需要完成的工作、以及部署Cloud Volumes ONTAP 時的考量事項。 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= 公有雲的先決條件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_prereq_onprem.html["先前版本：內部部署的先決條件。"]

在安裝Cloud Manager連接器及Cloud Volumes ONTAP 進行SnapMirror的不中斷和設定之前、我們必須先為雲端環境做一些準備。本頁說明需要完成的工作、以及部署Cloud Volumes ONTAP 時的考量事項。



== Cloud Manager與Cloud Volumes ONTAP 解決方案的部署先決條件檢查清單

* NetApp Cloud Central登入
* 從網頁瀏覽器存取多個端點的網路
* 連接器的網路位置
* 雲端供應商權限
* 個別服務的網路功能


如需開始使用所需資訊的詳細資訊、請造訪我們的 https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["雲端文件"^]。



== 考量



=== 1.什麼是Cloud Manager連接器？

在大多數情況下、Cloud Central帳戶管理員必須在雲端或內部部署網路中部署連接器。此連接器可讓Cloud Manager管理公有雲環境中的資源和程序。

如需更多有關連接器的資訊、請造訪我們的 https://docs.netapp.com/us-en/occm/concept_connectors.html["雲端文件"^]。



=== 2、規模與架構的不二之一Cloud Volumes ONTAP

部署Cloud Volumes ONTAP 時、您可以選擇預先定義的套件、或是建立自己的組態。雖然這些值中有許多可以稍後在不中斷營運的情況下加以變更、但根據要部署到雲端的工作負載、在部署之前仍需做出一些重要決策。

每個雲端供應商都有不同的部署選項、而且幾乎每個工作負載都有自己獨特的屬性。NetApp擁有 https://cloud.netapp.com/cvo-sizer["CVO規模調整工具"^] 這有助於根據容量和效能來正確調整部署規模、但它是以一些基本概念為建置基礎、值得考慮：

* 所需容量
* 雲端虛擬機器的網路功能
* 雲端儲存設備的效能特性


關鍵在於規劃的組態不僅能滿足目前的容量與效能需求、也能展望未來成長。這通常稱為容量保留空間和效能保留空間。

如果您想要進一步資訊、請閱讀有關正確規劃的文件 https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^]、 https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azure"^]和 https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["GCP"^]。



=== 3.單一節點或高可用度？

在所有雲端中、都有選項可在單一節點或叢集式高可用度配對中、與兩個節點部署CVO。視使用案例而定、您可能希望部署單一節點以節省成本、或是部署HA配對以提供更高的可用度和備援。

對於災難恢復使用案例或是將暫用儲存設備轉成開發與測試用途、單一節點是常見的、因為突然發生的分區或基礎架構中斷所造成的影響較低。然而、對於任何正式作業使用案例、如果資料只位於單一位置、或資料集必須擁有更多備援和可用度、則建議使用高可用度。

如需每個雲端高可用度版本架構的詳細資訊、請參閱的文件 https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^]、 https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azure"^] 和 https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["GCP"^]。

link:hybrid_dbops_snapcenter_getting_started.html["下一步：入門概述。"]
