---
sidebar: sidebar 
permalink: databases/sql-srv-anf_overview.html 
keywords: use case, rehosting, enterprise resource planning, RDBMS, cloud migration 
summary: 本文件涵蓋SQL Server全年無休可用度群組（AOAG）的即時部署、以Azure NetApp Files 利運用Azure虛擬機器。 
---
= TR-4897：Azure NetApp Files 《SQL Server on Real-Deployment View》（英文）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本文件涵蓋SQL Server全年無休可用度群組（AOAG）的即時部署、以Azure NetApp Files 利運用Azure虛擬機器。

NetApp公司Niyazz Mohamed

IT組織正面臨不斷變化的挑戰。Gartner報告、到2022年、將近75%的資料庫都需要雲端型儲存設備。Microsoft SQL Server是領先業界的關係式資料庫管理系統（RDBMS）、是Windows平台設計的應用程式和組織的首選、這些應用程式和組織仰賴SQL Server、從企業資源規劃（ERP）到分析、到內容管理、都能滿足各種需求。SQL Server協助企業革新管理大量資料集的方式、並推動應用程式滿足架構和查詢效能需求。

大多數IT組織都採用雲端優先方法。處於轉型階段的客戶會評估目前的IT環境、然後根據評估與探索練習、將資料庫工作負載移轉至雲端。促使客戶移轉雲端的因素包括彈性/突發、資料中心結束、資料中心整合、生命週期結束案例、合併、 併購等。移轉的原因可能因組織及其各自的業務優先順序而異。移轉至雲端時、選擇適當的雲端儲存設備是非常重要的、以便釋放SQL Server資料庫雲端部署的威力。



== 使用案例

將SQL Server基礎架構移轉至Azure、並將SQL Server與Azure廣泛的平台即服務（PaaS）功能整合、例如Azure Data Factory、Azure IoT Hub和Azure Machine Learning、為支援數位轉型創造了巨大的商業價值。相較於採用CAPEX模式或傳統私有雲端模式、採用雲端也能讓個別業務單位專注於生產力、並更快提供新功能和增強功能（DevTest使用案例）。本文件涵蓋SQL Server全年無休可用度群組（AOAG）的即時部署、以Azure NetApp Files 利運用Azure虛擬機器。

提供企業級儲存設備、並提供持續可用的檔案共用。Azure NetApp FilesSMB檔案共用區上的SQL Server正式作業資料庫需要持續可用的共用區、以確保節點永遠可以存取資料庫儲存區、包括在控制器升級或故障等中斷情況下。持續可用的檔案共用可免除在儲存節點之間複寫資料的需求。支援不中斷營運（NDOS）的SMB 3.0橫向擴充、持續處理及透明容錯移轉、以因應計畫性和非計畫性停機事件、包括許多管理工作。Azure NetApp Files

規劃雲端移轉時、您應該一律評估最佳的使用方法。應用程式移轉最常見且最簡單的方法是移轉（也稱為移轉和移轉）。本文所提供的範例案例使用重新託管方法。Azure虛擬機器上的SQL Server Azure NetApp Files 搭配使用功能、可讓您在雲端上使用完整版本的SQL Server、而無需管理內部部署的硬體。SQL Server虛擬機器（VM）也能在您隨付隨付的情況下簡化授權成本、並為開發、測試和重新整理資源環境提供彈性和突增功能。
