---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-technology.html 
keywords: technology, vmware cloud foundation, vsphere, nsx, snapcenter, veeam, VMware Cloud on AWS, Amazon FSx 
summary: 本節概述推動本解決方案的各種技術元件。 
---
= 技術
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-solution-overview.html["上一篇：解決方案總覽。"]

此解決方案包含NetApp、VMware、Amazon Web Services（AWS）和Veeam的創新技術。



== VMware



=== VMware Cloud Foundation

VMware Cloud Foundation平台整合了多種產品、可讓系統管理員在異質環境中配置邏輯基礎架構。這些基礎架構（稱為網域）可在私有和公有雲之間提供一致的作業。隨附Cloud Foundation軟體的材料清單、可識別預先驗證且符合資格的元件、以降低客戶的風險並簡化部署。

Cloud Foundation BOM的元件包括：

* Cloud Builder
* SDDC管理程式
* VMware vCenter Server設備
* VMware ESXi
* VMware NSX
* VRealize Automation
* VRealize Suite生命週期管理程式
* vRealize記錄洞見


如需VMware Cloud Foundation的詳細資訊、請參閱 https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware Cloud Foundation文件"^]。



=== VMware vSphere

VMware vSphere是一種虛擬化平台、可將實體資源轉換成運算、網路和儲存資源集區、以滿足客戶的工作負載和應用程式需求。VMware vSphere的主要元件包括：

* * ESXi。*此VMware Hypervisor可抽象化運算處理器、記憶體、網路及其他資源、並可用於虛擬機器和容器工作負載。
* * vCent.* VMware vCenter提供集中管理體驗、可與虛擬基礎架構中的運算資源、網路和儲存設備互動。


客戶運用NetApp ONTAP 解決方案與深度產品整合、強大支援、強大功能和儲存效率、打造強大的混合式多雲端、充分發揮vSphere環境的完整潛能。

如需VMware vSphere的詳細資訊、請參閱 https://docs.vmware.com/en/VMware-vSphere/index.html["此連結"^]。

如需NetApp解決方案搭配VMware的詳細資訊、請參閱 https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html["此連結"^]。



=== VMware NSX

VMware NSX通常稱為網路Hypervisor、採用軟體定義模式來連接虛擬化工作負載。VMware NSX在內部部署和AWS上的VMware Cloud中隨處可見、可為客戶應用程式和工作負載提供網路虛擬化和安全性。

如需VMware NSX的詳細資訊、請參閱 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/index.html["此連結"^]。



== NetApp



=== NetApp ONTAP

NetApp ONTAP 解決方案是VMware vSphere環境的領導級儲存解決方案、已有將近二十年的歷史、持續增加創新功能來簡化管理、同時降低成本。搭配vSphere使用VMware是一項絕佳組合、可降低主機硬體與VMware軟體的費用。ONTAP您也可以利用一致的高效能、以較低的成本保護資料、同時充分發揮原生儲存效率。

如需NetApp ONTAP 產品的詳細資訊、請參閱 https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html["此連結"^]。



=== 適用於ONTAP VMware的NetApp產品

VMware的支援VMware的VMware工具將多個外掛程式整合到單一虛擬應用裝置中、為使用NetApp儲存系統的VMware環境中的虛擬機器提供端點對端點生命週期管理。ONTAPVMware的VMware工具包括：ONTAP

* *虛擬儲存主控台（VSC）。*使用NetApp儲存設備、為VM和資料存放區執行全方位的管理工作。
* *適用於ONTAP VMware的VASA Provider for SONT.*可利用VMware虛擬磁碟區（vVols）和NetApp儲存設備、實現儲存原則型管理（SPBM）。
* *儲存複寫介面卡（SRA）*。在搭配VMware Site Recovery Manager（SRM）時、若發生故障、可恢復vCenter資料存放區和虛擬機器。


VMware的支援VMware的VMware工具不僅能讓使用者管理外部儲存設備、也能與vVols和VMware Site Recovery Manager整合。ONTAP如此一來、您就能更輕鬆地從vCenter環境中部署及操作NetApp儲存設備。

如需更多ONTAP 有關適用於VMware的NetApp產品介紹工具的資訊、請參閱 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["此連結"^]。



=== NetApp SnapCenter

NetApp SnapCenter 流通軟體是易於使用的企業平台、可安全地協調及管理應用程式、資料庫及檔案系統之間的資料保護。透過將這些工作卸載給應用程式擁有者、而不犧牲監控和管理儲存系統活動的能力、從而簡化備份、還原和複製生命週期管理。SnapCenter藉由運用儲存型資料管理功能、SnapCenter 使得效能與可用度提升、同時縮短測試與開發時間。

VMware vSphere的VMware vSphere支援當機一致且VM一致的備份與還原作業、適用於虛擬機器（VM）、資料存放區和虛擬機器磁碟（VMDK）SnapCenter 。它也支援SnapCenter 特定於應用程式的支援功能外掛程式、以保護虛擬化資料庫和檔案系統的應用程式一致備份與還原作業。

如需NetApp SnapCenter 產品的詳細資訊、請參閱 https://docs.netapp.com/us-en/snapcenter/["此連結"^]。



== 第三方資料保護



=== Veeam備份與複寫

Veeam備份與複寫是適用於雲端、虛擬及實體工作負載的備份、還原及資料管理解決方案。Veeam備份與複寫與NetApp Snapshot技術的專業整合、可進一步保護vSphere環境。

如需Veeam備份與複寫的詳細資訊、請參閱 https://www.veeam.com/vm-backup-recovery-replication-software.html["此連結"^]。



== 公有雲



=== AWS身分識別與存取管理

AWS環境包含各式各樣的產品、包括運算、儲存、資料庫、網路、分析、 以及更多協助解決業務挑戰的功能。企業必須能夠定義哪些人有權存取這些產品、服務和資源。同樣重要的是、您也必須決定允許使用者在哪些情況下操作、變更或新增組態。

AWS身分識別與存取管理（AIAP）提供安全的控制面板、可管理AWS服務與產品的存取。適當設定的使用者、存取金鑰和權限、可在AWS和Amazon FSX上部署VMware Cloud。

如需有關Aim的詳細資訊、請參閱 https://docs.aws.amazon.com/iam/index.html["此連結"^]。



=== AWS上的VMware Cloud

AWS上的VMware Cloud可將VMware企業級SDDC軟體導入AWS Cloud、並針對原生AWS服務進行最佳化存取。以VMware Cloud Foundation為後盾、AWS上的VMware Cloud整合了VMware的運算、儲存設備和網路虛擬化產品（VMware vSphere、VMware vSAN和VMware NSX）、以及經過最佳化的VMware vCenter Server管理功能、可在專屬、靈活、裸機的AWS基礎架構上執行。

如需AWS上VMware Cloud的詳細資訊、請參閱 https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html["此連結"^]。



=== Amazon FSX for NetApp ONTAP 產品

Amazon FSX for NetApp ONTAP 的功能完整且完全受管理ONTAP 的功能完善的支援系統、可作為原生AWS服務。以NetApp ONTAP 支援為基礎、提供熟悉的功能、同時提供完整託管雲端服務的簡易性。

Amazon FSX ONTAP for VMware可為各種運算類型提供多重傳輸協定支援、包括公有雲或內部部署的VMware。Amazon FSX for ONTAP the支援目前與訪客連線的使用案例、以及技術預覽中的NFS資料存放區、讓企業能夠從內部部署環境和雲端中、充分利用熟悉的功能。

如需Amazon FSX for NetApp ONTAP 功能的詳細資訊、請參閱 https://aws.amazon.com/fsx/netapp-ontap/["此連結"]。

link:aws-guest-dr-overview.html["下一步：總覽- AWS來賓連線儲存災難恢復。"]
