---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-config.html 
keywords: secondary, windows, snapcenter server, veeam server 
summary: 若要將應用程式VM和資料庫Volume容錯移轉至執行於AWS的VMware Cloud Volume服務、您必須同時安裝SnapCenter 並設定執行中的VMware Server和Veeam備份與複寫伺服器執行個體。容錯移轉完成後、您也必須設定這些工具、以便恢復正常的備份作業、直到規劃並執行內部部署資料中心的容錯回復為止。 
---
= 雲端備份工具與組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-config-veeam.html["先前版本：部署及設定Veeam備份伺服器。"]

若要將應用程式VM和資料庫Volume容錯移轉至執行於AWS的VMware Cloud Volume服務、您必須同時安裝SnapCenter 並設定執行中的VMware Server和Veeam備份與複寫伺服器執行個體。容錯移轉完成後、您也必須設定這些工具、以便恢復正常的備份作業、直到規劃並執行內部部署資料中心的容錯回復為止。



== 部署次要Windows SnapCenter 功能伺服器

支援VMware Cloud SDDC部署的VMware伺服器、或安裝在VPC中的EC2執行個體上、並可透過網路連線至VMware Cloud環境。SnapCenter

NetApp支援網站提供支援軟體、可安裝在位於網域或工作群組的Microsoft Windows系統上。SnapCenter如需詳細的規劃指南和安裝指示、請參閱 https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["NetApp文件中心"^]。

您可以在找到SnapCenter 該軟件 https://mysupport.netapp.com["此連結"^]。



== 設定次要Windows SnapCenter 靜態伺服器

若要還原鏡射至FSXS庫ONTAP 的應用程式資料、您必須先執行內部部署SnapCenter 的整套還原資料庫。完成此程序後、將重新建立與VM的通訊、並使用FSX還原ONTAP 做為主要儲存設備來恢復應用程式備份。

若要達成此目標、您必須在SnapCenter the努力伺服器上完成下列項目：

. 將電腦名稱設定為與原始內部部署SnapCenter 的內部部署伺服器相同。
. 設定網路功能、以便與VMware Cloud和FSX ONTAP 支援例項進行通訊。
. 完成還原SnapCenter 整套程序以還原整個資料庫。
. 確認SnapCenter 支援功能為災難恢復模式、以確保FSX現在是備份的主要儲存設備。
. 確認已與還原的虛擬機器重新建立通訊。


如需完成這些步驟的詳細資訊、請參閱「到」一節 link:aws-guest-dr-failover.html#snapcenter-database-restore-process["資料庫還原程序SnapCenter"]。



== 部署次要Veeam備份與複寫伺服器

您可以將Veeam備份與複寫伺服器安裝在AWS或EC2執行個體上VMware Cloud的Windows伺服器上。如需詳細的實作指南、請參閱 https://www.veeam.com/documentation-guides-datasheets.html["Veeam說明中心技術文件"^]。



== 設定次要Veeam備份與複寫伺服器

若要還原已備份至Amazon S3儲存設備的虛擬機器、您必須在Windows伺服器上安裝Veeam伺服器、並將其設定為與VMware Cloud、FNSX ONTAP 及包含原始備份儲存庫的S3儲存庫進行通訊。此外、還必須在FSX ONTAP 更新上設定新的備份儲存庫、以便在VM還原後進行新的備份。

若要執行此程序、必須完成下列項目：

. 設定網路功能、以便與VMware Cloud、FSX ONTAP 功能區及內含原始備份儲存庫的S3儲存區進行通訊。
. 將FSXSf2 ONTAP 上的SMB共用區設定為新的備份儲存庫。
. 將原本作為橫向擴充備份儲存庫一部分的S3儲存庫掛載到內部部署。
. 還原VM之後、請建立新的備份工作來保護SQL和Oracle VM。


如需使用Veeam還原VM的詳細資訊、請參閱一節 link:aws-guest-dr-restore-veeam-full.html["使用Veeam完整還原還原應用程式VM"]。

link:aws-guest-dr-snapcenter-db-backup.html["下一步：SnapCenter 適用於災難恢復的資料庫備份。"]
