---
sidebar: sidebar 
permalink: ehc/aws/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= 適用於AWS VMC的NetApp功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
深入瞭解NetApp為AWS VMware Cloud（VMC）帶來的功能：從NetApp做為來賓連線儲存設備或原生資料存放區、移轉工作流程、延伸/突增至雲端、備份/還原及災難恢復。

從下列選項中選取、跳至所需內容的區段：

* link:#config["在AWS中設定VMC"]
* link:#datastore["適用於VMC的NetApp儲存選項"]




== 在AWS中設定VMC

如同內部部署、規劃雲端型虛擬化環境對於成功建立虛擬機器和移轉的正式作業就緒環境來說、是非常重要的。

本節說明如何在AWS SDDC上設定及管理VMware Cloud、並搭配可用的選項來連接NetApp儲存設備。


NOTE: 客體內儲存設備是唯一受支援的方法、可將FSXVMware ONTAP 和Cloud Volumes ONTAP VMware連接至AWS VMC。

設定程序可分為下列步驟：

* link:aws-setup.html#deploy["部署及設定適用於AWS的VMware Cloud"]
* link:aws-setup.html#connect["將VMware Cloud連接至FSX ONTAP VMware"]




== 適用於VMC的NetApp儲存選項

NetApp儲存設備可在AWS VMC中以多種方式使用、無論是猜測已連線、或是做為原生資料存放區。

請造訪 link:ehc-support-configs.html["支援的NetApp儲存選項"] 以取得更多資訊。

AWS支援下列組態的NetApp儲存設備：

*來賓連線儲存設備*

* link:aws-guest.html#fsx-ontap["FSX ONTAP 支援以客為本的連線儲存設備"]
* link:aws-guest.html#cvo["以客體連線儲存設備形式提供的資訊（CVO）Cloud Volumes ONTAP"]


*原生資料存放區*

* link:https://blogs.vmware.com/cloud/2021/12/01/vmware-cloud-on-aws-going-big-reinvent2021/["FSX ONTAP 支援原生資料存放區"^]



NOTE: 1 -目前處於私有預覽中
