---
sidebar: sidebar 
permalink: vmware/migrate-vms-to-ec2-fsxn.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: 本技術報告涵蓋如何使用 Cirrus 移轉雲端（ CMC ）的「移轉作業資料行動資料即程式碼」功能、將內部部署的 VMware vSphere VM 移轉至 Amazon EC2 執行個體、並將資料磁碟放在 FSX ONTAP iSCSI LUN 上。 
---
= 使用 Amazon xon FSX for ONTAP 將 VM 移轉至 Amazon EC2 ：概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
組織正在加速移轉至 AWS 上的雲端運算解決方案、利用 Amazon Elastic Compute Cloud （ Amazon EC2 ）執行個體和 Amazon FSX for NetApp ONTAP （ FSX ONTAP ）等服務、將 IT 基礎架構現代化、節省成本並改善營運效率。這些 AWS 產品可讓移轉作業透過消費型定價模式、企業儲存功能、最佳化總持有成本（ TCO ）、提供靈活度和擴充性、以因應不斷演變的全球業務需求。



== 總覽

對於深入投資 VMware vSphere 的企業而言、根據目前的市場情況、移轉至 AWS 是一項具成本效益的選項、提供獨特的商機。

隨著這些組織移轉至 AWS 、他們想要善用雲端的敏捷度和成本效益、同時保留熟悉的功能集、尤其是儲存設備。在移轉工作負載或設定災難恢復解決方案時、以熟悉的儲存傳輸協定（尤其是 iSCSI ）來維持無縫作業、是非常重要的。

使用 AWS 託管儲存服務 FSX ONTAP 來保留企業儲存功能、也就是來自內部部署的任何第三方廠商儲存設備、企業就能充分發揮 AWS 的強大功能、同時將中斷情形降至最低、並將未來投資最大化。

本技術報告涵蓋如何使用 Cirrus 移轉雲端（ CMC ）的「資料移動即程式碼」功能、將內部部署的 VMware vSphere VM 移轉至 Amazon EC2 執行個體、並將資料磁碟放在 FSX ONTAP iSCSI LUN 上。



== 解決方案需求

VMware 客戶目前正尋求解決許多挑戰。這些組織希望：

. 運用企業儲存功能、例如精簡配置、儲存效率技術、零佔用空間的複本、整合式備份、區塊層級複寫、 和分層。這有助於從第 1 天起、在 AWS 上最佳化移轉工作和未來部署。
. 透過結合 FSX ONTAP 及其提供的成本最佳化功能、最佳化目前在使用 Amazon EC2 執行個體的 AWS 上的儲存部署。
. 透過適當調整 Amazon EC2 執行個體規模以符合所需的 IOPS 和處理量參數、降低使用 Amazon EC2 執行個體搭配區塊儲存解決方案的總擁有成本（ TCO ）。Amazon EC2 磁碟營運採用區塊儲存技術、可提供頻寬和 I/O 速率上限。使用 FSX ONTAP 的檔案儲存使用網路頻寬。換句話說、 FSX ONTAP 沒有 VM 層級的 I/O 限制。




== 技術元件總覽



=== FSX ONTAP 概念

Amazon FSX ONTAP 是完全託管的 AWS 儲存服務、可在 AWS 上提供 NetApp ® ONTAP ® 檔案系統、以及所有熟悉的 ONTAP 資料管理功能、效能和 API 。其高效能儲存設備支援多種傳輸協定（ NFS 、 SMB 、 iSCSI ）、可為使用 Windows 、 Linux 和 macOS EC2 執行個體的工作負載提供單一服務。

由於 FSX ONTAP 是 ONTAP 檔案系統、因此它提供許多熟悉的 NetApp 功能和服務、包括 SnapMirror ® 資料複寫技術、精簡複本和 NetApp Snapshot ™複本。透過資料分層來善用低成本容量層、 FSX ONTAP 具有彈性、幾乎可實現無限擴充。此外、利用 NetApp 的招牌儲存效率技術、它還能進一步降低 AWS 的儲存成本。如需詳細link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSX ONTAP 快速入門"]資訊、請參閱。



==== 檔案系統

FSX ONTAP 的核心資源是以固態硬碟（ SSD ）儲存設備為基礎的檔案系統。在配置 FSX ONTAP 檔案系統時、使用者會輸入所需的處理量和儲存容量、然後選取檔案系統所在的 Amazon VPC 。

使用者也可以選擇檔案系統的兩種內建高可用度部署模式：多可用度區域（ AZ ）或單一 AZ 部署。每個選項都提供其本身的耐用度與可用度等級、客戶可根據使用案例的營運持續性需求來選擇。多個 AZ 部署由雙節點組成、可在兩個 AZs 之間無縫複寫。成本最佳化的單一 AZ 部署選項可在兩個節點中、將檔案系統分成兩個不同的故障網域、這兩個網域都位於單一 AZ 內。儲存虛擬機器 FSX ONTAP 檔案系統中的資料是透過稱為儲存虛擬機器（ SVM ）的邏輯儲存分割區來存取。SVM 實際上是其本身的檔案伺服器、配備自己的資料和管理存取點。在 FSX ONTAP 檔案系統上存取 iSCSI LUN 時、 Amazon EC2 執行個體會使用 SVM 的 iSCSI 端點 IP 位址、直接與 SVM 介面。

雖然在叢集中維護單一 SVM 是可行的、但在叢集中執行多個 SVM 的選項有廣泛的用途和優點。客戶可以考量其業務需求、包括工作負載隔離的需求、來決定要設定的 SVM 最佳數量。



==== 磁碟區

FSX ONTAP SVM 中的資料會儲存並組織在稱為 Volume 的結構中、這些結構會做為虛擬容器。可以使用單一或多個 LUN 來設定個別磁碟區。儲存在每個磁碟區的資料會消耗檔案系統中的儲存容量。然而、由於 FSX ONTAP 精簡配置了磁碟區、因此磁碟區只會佔用儲存資料量的儲存容量。



=== Cirrus 移轉雲端移轉作業概念

CMC 是 Cirrus Data Solutions 、 Inc. 提供的可轉譯軟體即服務（ SaaS ）產品、可透過 AWS Marketplace 取得。MigrateOps 是 CMC 的「資料行動即程式碼」自動化功能、可讓您使用 YAML 中的簡單操作組態、以宣告方式大規模管理資料移動性作業。移轉作業組態可決定您要如何執行資料移動性工作。若要深入瞭解 MigrateOps 、請參閱 link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["關於 MigrateOps"]。

MigrateOps 採用自動化第一的方法、這是專為簡化整個流程而打造、確保雲端規模的企業資料移動性、而不會中斷營運。除了 CMC 提供的功能豐富的自動化功能之外、 MigrateOps 還會進一步新增其他通常由外部管理的自動化功能、例如：

* 作業系統補救
* 應用程式轉換與核准排程
* 零停機叢集移轉
* 公有雲 / 私有雲平台整合
* 虛擬化平台整合
* 企業儲存管理整合
* SAN （ iSCSI ）組態


在上述工作完全自動化的情況下、準備內部部署來源虛擬機器（例如新增 AWS 代理程式和工具）、建立目的地 FSX LUN 、在 AWS 目的地執行個體設定 iSCSI 和多重路徑 /MPIO 的所有繁瑣步驟、 只要在 YAML 檔案中指定參數、就能免除停止 / 啟動應用程式服務的所有工作。

FSX ONTAP 可提供資料 LUN 及 Amazon EC2 執行個體類型的適當大小、同時提供組織先前在內部環境中所擁有的所有功能。CMC 的「移轉作業」功能將用於自動化所有相關步驟、包括佈建對應的 iSCSI LUN 、使其成為可預測的宣告式作業。

* 注意 * ： CMC 需要在來源和目的地虛擬機器執行個體上安裝超精簡代理程式、才能確保從儲存來源儲存設備傳輸至 FSX ONTAP 的資料安全無虞。



== 搭配 EC2 執行個體使用 Amazon FSX ONTAP 的優點

適用於 Amazon EC2 執行個體的 FSX ONTAP 儲存設備可提供多項優點：

* 高處理量及低延遲儲存設備、可為要求最嚴苛的工作負載提供一致的高效能
* 智慧型 NVMe 快取可改善效能
* 可調整的容量、處理量和 IOP 可即時變更、並可快速因應不斷變化的儲存需求
* 從內部部署 ONTAP 儲存設備到 AWS 的區塊型資料複寫
* 多重傳輸協定存取功能、包括 iSCSI 、可廣泛用於內部部署的 VMware 部署
* NetApp Snapshot ™技術和由 SnapMirror 協調的災難恢復功能可防止數據丟失並加快恢復速度
* 儲存效率功能可減少儲存佔用空間和成本、包括精簡配置、重複資料刪除、壓縮及壓縮
* 高效複寫可將建立備份所需的時間從數小時縮短為數分鐘、並將 RTO 最佳化
* 使用 NetApp SnapCenter ® 進行檔案備份與還原的精細選項


將採用 FSX ONTAP 的 Amazon EC2 執行個體部署為 iSCSI 型儲存層、可提供高效能、關鍵任務資料管理功能、以及降低成本的儲存效率功能、協助您在 AWS 上進行部署。

執行 Flash Cache 、多個 iSCSI 工作階段、並運用 5% 的工作集大小、 FSX ONTAP 可提供高達 350K 的 IOPS 、即使是最密集的工作負載、也能提供高效能等級。

由於只會針對 FSX ONTAP 套用網路頻寬限制、而非區塊儲存頻寬限制、因此使用者可以利用小型 Amazon EC2 執行個體類型、同時達到與大型執行個體類型相同的效能速率。使用這類小型執行個體類型也能降低運算成本、最佳化 TCO 。

FSX ONTAP 服務多種傳輸協定的能力是另一項優勢、可協助標準化單一 AWS 儲存服務、滿足各種現有資料和檔案服務需求。對於深入投資 VMware vSphere 的企業而言、根據目前的市場情況、移轉至 AWS 是一項具成本效益的選項、提供獨特的商機。
