---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-hybrid-multicloud.html 
keywords: vmware, getting, started, overview, netapp, hybrid, multicloud, multi, cloud 
summary:  
---
= 混合式多雲端
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware 混合式多雲端架構搭配 NetApp ，可在內部部署基礎架構與公有雲服務之間順暢整合，提供靈活度與擴充性。



== 簡介

這種方法可讓企業輕鬆移轉工作負載，最佳化資源使用率，並在兩種環境中維持一致的作業。

如需 VMware 和 NetApp 混合雲方案的詳細資訊，請參閱link:https://docs.netapp.com/us-en/netapp-solutions/ehc/ehc-overview.html#vmware-cloud-options-in-public-cloud["NetApp混合式多雲端與VMware的總覽"]。



== 使用 NetApp 的 VMware 部署案例

本節說明跨內部部署和公有雲的 VMware 環境各種部署選項。每個雲端供應商都在各自的公有雲產品中支援 VMware 軟體定義資料中心（ SDDC ）和 / 或 VMware Cloud Foundation （ VCF ）堆疊。

* * VMware 內部部署 *


將 VMware 與內部部署的 NetApp 儲存設備搭配使用，可提供強大，可擴充且靈活的虛擬化環境。透過將 NetApp 的進階資料管理功能（例如重複資料刪除，壓縮和高效快照）與採用 ONTAP 技術的適當儲存系統配對，客戶可以選擇適合他們的平台。這項組合可確保虛擬化工作負載的高效能，可靠性及簡化管理，進而提升整體資料中心效率。

* * Azure VMware 解決方案 *


Azure VMware解決方案是一種混合雲服務、可在Microsoft Azure公有雲中提供功能完整的VMware SDDC。Azure VMware解決方案是第一方的解決方案、由Microsoft完全管理及支援、並由VMware運用Azure基礎架構進行驗證。這表示當部署Azure VMware解決方案時、客戶會獲得VMware的ESXi用於運算虛擬化、vSAN用於超融合式儲存設備、 以及NSX的網路與安全功能、同時充分利用Microsoft Azure的全球知名度、領先同級的資料中心設施、以及接近豐富的原生Azure服務與解決方案生態系統。

* * VMware Cloud on AWS *


AWS上的VMware Cloud可將VMware企業級SDDC軟體導入AWS Cloud、並針對原生AWS服務進行最佳化存取。以VMware Cloud Foundation為後盾、AWS上的VMware Cloud整合了VMware的運算、儲存和網路虛擬化產品（VMware vSphere、VMware vSAN和VMware NSX）、以及VMware vCenter Server管理功能、經過最佳化、可在專屬、靈活、裸機的AWS基礎架構上執行。

* * Google Cloud VMware Engine*


Google Cloud VMware Engine 是一項基礎架構即服務（ IaaS ）產品，以 Google Cloud 的高效能可擴充基礎架構和 VMware Cloud Foundation 堆疊（ VMware vSphere ， vCenter ， vSAN 和 NSS-T ）為基礎。此服務可讓您快速移轉至雲端，順暢地將現有的 VMware 工作負載從內部環境移轉或擴充至 Google Cloud Platform ，而無需花費成本，精力或風險重新架構或重新設計應用程式。這項服務是由Google銷售及支援的服務、與VMware密切合作。
