---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= FC 上的 VMFS 做為 VCF 主要資料存放區
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此案例中，我們將示範如何使用光纖通道（ FC ）後端部署 VMFS 資料存放區，以用於管理和工作負載網域。

作者： Suresh ThopPay



== 案例總覽

Vcf Principal 儲存設備是指任何類型的儲存設備，這些儲存設備是在 VCF 網域設定程序中部署，轉換或匯入的。本文件涵蓋下列案例。

[cols="20% 20% 20% 20% 20%"]
|===
| 儲存類型 | 管理網域 - 預設叢集 | 管理網域 - 其他叢集 | VI 工作負載網域 - 預設叢集 | VI 工作負載網域 - 其他叢集 


| FC 上的 VMFS | * 導入工具 * | * 匯入工具， SDDC API* | 是的 | 是的 
|===


== 先決條件

此案例需要下列元件和組態：

* ONTAP 儲存系統， FC 連接埠連接至 FC 交換器。
* SVM 是以 FC 生命來建立的。
* vSphere 搭配 FC HBA 連線至 FC 交換器。
* 在 FC 交換器上設定單一啟動器目標分區。
+

NOTE: 在區域組態中使用 SVM FC 邏輯介面，而非在 ONTAP 系統上使用實體 FC 連接埠。



NetApp 建議 FC LUN 採用多重路徑。



== 部署步驟



=== 管理網域 - 預設叢集

初始叢集上的 FC 主要儲存設備僅支援 VCF 瀏覽欄位匯入工具。如果使用 cloudbuilder 工具（直到版本 5.2.x ）部署 VCF ，則僅支援 VSAN 。如需詳細資訊，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["將現有 vSphere 環境轉換為管理網域"]。



=== 管理網域 - 其他叢集

管理網域上的其他 vSphere 叢集可透過下列選項進行部署： * 在 vSphere 環境中有其他叢集，並使用 VCF 瀏覽欄位匯入工具將 vSphere 環境轉換為管理網域。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["VMware vSphere適用的工具ONTAP"]， https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["系統管理員或 ONTAP API"]可用於將 VMFS 資料存放區部署至 vSphere 叢集。* 使用 SDDC API 部署額外的叢集。vSphere 主機應已設定 VMFS 資料存放區。用於 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["系統管理員或 ONTAP API"]將 LUN 部署至 vSphere 主機。* 使用 SDDC Manager UI 來部署其他叢集。但此選項只會建立 VSAN 資料存放區，直到版本 5.2.x 為止



=== VI 工作負載網域 - 預設叢集

管理網域啟動並執行後，可使用 SDDC Manager UI 建立 VI 工作負載網域 * 。vSphere 主機應已設定 VMFS 資料存放區。使用系統管理員或 ONTAP API 將 LUN 部署至 vSphere 主機。* 將現有 vSphere 環境匯入為新的 VI 工作負載網域。適用於 VMware vSphere ， System Manager 或 ONTAP API 的 ONTAP 工具可用於將 VMFS 資料存放區部署至 vSphere 叢集。



=== VI 工作負載網域 - 其他叢集

VI 工作負載啟動並執行後，可使用下列選項，在 FC LUN 上使用 VMFS 部署其他叢集。

* 使用 VCF 瀏覽欄位匯入工具匯入 vSphere 環境中的其他叢集。適用於 VMware vSphere ， System Manager 或 ONTAP API 的 ONTAP 工具可用於將 VMFS 資料存放區部署至 vSphere 叢集。
* 使用 SDDC Manager UI 或 API 來部署其他叢集。vSphere 主機應已設定 VMFS 資料存放區。使用系統管理員或 ONTAP API 將 LUN 部署至 vSphere 主機。




== 其他資訊

如需設定 ONTAP 儲存系統的相關資訊、請參閱 link:https://docs.netapp.com/us-en/ontap["供應說明文件ONTAP"] 中心。

如需設定 VCF 的相關資訊link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation 文件"]，請參閱。
