---
sidebar: sidebar 
permalink: vmware/vmware-scv-overview.html 
keywords: netapp, vmware, getting, started 
summary:  
---
= VMware vSphere的插件SnapCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
適用於 VMware vSphere 的 SnapCenter 外掛程式可為虛擬機器（ VM ）、資料存放區和 VMDK 提供快速、高效且符合 VM 需求的備份與還原作業。它可與 SnapCenter 伺服器搭配運作、為 SnapCenter 應用程式專屬外掛程式提供應用程式型備份與還原功能。



== 文件資源

如需詳細資訊、請參閱下列文件資源。

* link:https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/["VMware vSphere文件的VMware外掛程式SnapCenter"]




== 解決方案資源

請參閱下列 3-2-1 備份解決方案、其中包含適用於 VMware vSphere 的 SnapCenter 外掛程式、以及適用於 VM 的 BlueXP 備份與還原功能。

技術報告： link:../ehc/bxp-scv-hybrid-solution.html["適用於 VMware 的 3-2-1 Data Protection 、搭配 SnapCenter 外掛程式、以及適用於 VM 的 BlueXP 備份與還原"]

Tech OnTap 部落格： link:https://community.netapp.com/t5/Tech-ONTAP-Blogs/3-2-1-Data-Protection-for-VMware-with-SnapCenter-Plug-in-and-BlueXP-backup-and/ba-p/446180["適用於 VMware 的 3-2-1 Data Protection 、搭配 SnapCenter 外掛程式、以及適用於 VM 的 BlueXP 備份與還原"]



== 視訊資源

.VMware vSphere的解決方案外掛程式-解決方案先決條件SnapCenter
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto]
.VMware vSphere的VMware外掛程式- SnapCenter 部署
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto]
.VMware vSphere的VMware外掛程式-備份工作流程SnapCenter
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto]
.VMware vSphere的VMware外掛程式-還原工作流程SnapCenter
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto]
.支援SQL還原工作流程SnapCenter
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto]