---
sidebar: sidebar 
permalink: ai/ai-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: AI導向的自動化與邊緣運算是一項領先業界的方法、可協助企業組織實現數位化轉型、並將作業效率與安全性最大化。利用邊緣運算技術、資料處理速度更快、因為資料中心不需要往返資料中心。因此、將資料來回傳送至資料中心或雲端的相關成本會降低。 
---
= 結論
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
AI導向的自動化與邊緣運算是一項領先業界的方法、可協助企業組織實現數位化轉型、並將作業效率與安全性最大化。利用邊緣運算技術、資料處理速度更快、因為資料中心不需要往返資料中心。因此、將資料來回傳送至資料中心或雲端的相關成本會降低。如果企業必須使用部署在邊緣的AI推斷模型、以近乎即時的方式做出決策、則降低延遲並加快速度將會更為有利。

NetApp儲存系統提供與本機SSD儲存設備相同或更好的效能、並為資料科學家、資料工程師、AI/ML開發人員、企業或IT決策者提供下列效益：

* 輕鬆在AI系統、分析和其他關鍵業務系統之間共享資料。這種資料共享可降低基礎架構的負荷、改善效能、並簡化整個企業的資料管理。
* 獨立擴充的運算與儲存設備、可將成本降至最低、並改善資源使用率。
* 利用整合式Snapshot複本與複製、簡化開發與部署工作流程、提供即時且節省空間的使用者工作區、整合式版本控制、以及自動化部署。
* 企業級的資料保護功能、可實現災難恢復與營運不中斷。本文所述的NetApp與Lenovo解決方案是靈活的橫向擴充架構、非常適合在邊緣部署企業級AI推斷。




== 感謝

* J.法爾坎格、資深聯想HPC與AI解決方案經理
* NetApp技術行銷工程師Dave Arettette
* NetApp E系列AI解決方案技術主管Joey Parnell
* NetApp品質保證工程師Cody Harman




== 何處可找到其他資訊

若要深入瞭解本文件所述資訊、請參閱下列文件和/或網站：

* NetApp AFF A系列陣列產品頁面
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* NetApp ONTAP 產品資料管理軟體：ONTAP 9資訊庫
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727：NetApp EF系列簡介
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* NetApp E系列SANtricity 產品介紹
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* NetApp容器持續儲存設備：NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* NetApp BlueXP 複製與同步
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* TensorFlow基準測試
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Lenovo ThinkSystem SE350 Edge Server
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Lenovo ThinkSystem DM5100F統一化Flash儲存陣列
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


