---
sidebar: sidebar 
permalink: ai/ai-sent-support-center-analytics.html 
keywords: tr-4910, tr4910, 4910, sentiment, analysis, customer value, support center, artificial intelligence 
summary: 本技術報告提供設計指南、協助客戶在企業級的全球支援中心、使用NetApp資料管理技術搭配NVIDIA軟體架構、使用傳輸學習和對話式AI來執行情緒分析。 
---
= TR-4910：客戶與NetApp AI溝通時的意見分析
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Rick Huang、Sathish Thyagarajan和David Arettette、NetApp Diego Sosa-COSA、SFL Scientific

[role="lead"]
本技術報告提供設計指南、協助客戶在企業級的全球支援中心、使用NetApp資料管理技術搭配NVIDIA軟體架構、使用傳輸學習和對話式AI來執行情緒分析。此解決方案適用於任何想要從記錄的語音或文字檔案中獲得客戶洞見的產業、這些檔案代表聊天記錄、電子郵件及其他文字或音訊通訊。我們實作了端點對端點傳輸途徑、在採用NetApp雲端連線的All Flash儲存設備的GPU加速運算叢集上、展示自動語音辨識、即時情緒分析、以及深度學習的自然語言處理模式重新訓練功能。您可以訓練並最佳化大量最先進的語言模式、以便與全球支援中心一起快速進行推論、以創造卓越的客戶體驗、以及客觀的長期員工績效評估。

情緒分析是自然語言處理（NLP）中的研究領域、可從文字中擷取正面、負面或中立的情緒。隨著越來越多人來與AI系統互動、對話式AI系統的整合程度已提升到接近全球的程度。情緒分析有多種使用案例、從判斷支援中心員工與來電者對話的績效、以及提供適當的自動回應、到根據公司代表與每季獲利拜訪對象之間的互動、預測公司的股票價格。此外、情緒分析可用來判斷客戶對於品牌所提供產品、服務或支援的看法。

此端點對端點解決方案使用NLP模型來執行高層級的意見分析、以實現支援中心的分析架構。錄音會以書面文字處理、並從對話中的每個句子擷取內容。彙總到儀表板的結果、可用來分析過去和即時的對話情緒。此解決方案可通用化為其他具有類似資料模式和輸出需求的解決方案。有了適當的資料、就能完成其他使用案例。例如、可以使用相同的端點對端點管道來分析公司的營收通話。其他形式的NLP分析、例如主題建模和命名實體辨識（NER）、也可能是因為管道的靈活特性。

NVIDIA Riva、NVIDIA TAO工具套件和NetApp DataOps工具套件共同實現了這些AI實作。NVIDIA的工具可用於使用預先建置的機型和管線、快速部署高效能的AI解決方案。NetApp DataOps Toolkit可簡化各種資料管理工作、加速開發。



== 客戶價值

企業可以從員工評估工具和客戶反應工具中、看到文字、音訊和視訊對話的價值、以便進行意見分析。主管可從儀表板中所顯示的資訊獲益、以便根據對話的雙方、對員工和客戶滿意度進行評估。

此外、NetApp DataOps Toolkit還能管理客戶基礎架構內的資料版本設定與分配。如此一來、儀表板內的分析功能就會頻繁更新、而不會產生難以管理的資料儲存成本。
