---
sidebar: sidebar 
permalink: ai/aicp_kubeflow_deployment_overview.html 
keywords: Kubeflow, Prerequisites, Kubernetes, cluster 
summary: NetApp 的開放原始碼 MLOps - Kubefflow 部署 
---
= Kubeflow部署
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本節說明在Kubernetes叢集中部署Kubeflow時、必須完成的工作。



== 先決條件

在您執行本節所述的部署練習之前、我們假設您已經執行下列工作：

. 您已經有一個運作中的 Kubernetes 叢集、而且您正在執行的 Kubernetes 版本受到您要部署的 Kubeflow 版本的支援。如需支援的 Kubernetes 版本清單、請參閱中 Kubeflow 版本的相依性 link:https://www.kubeflow.org/docs/releases/["官方Kubeflow文件"^]。
. 您已在 Kubernetes 叢集中安裝及設定 NetApp Trident 。如需 Trident 的詳細資訊、請參閱link:https://docs.netapp.com/us-en/trident/index.html["Trident文件"]。




== 設定預設Kubernetes StorageClass

在您部署 Kubeflow 之前、建議您在 Kubernetes 叢集中指定預設 StorageClass 。Kubeflow 部署程序可能會嘗試使用預設 StorageClass 來配置新的持續磁碟區。如果未將 StorageClass 指定為預設 StorageClass 、則部署可能會失敗。若要在叢集內指定預設StorageClass、請從部署跨接主機執行下列工作。如果您已在叢集內指定預設StorageClass、則可以跳過此步驟。

. 將現有的其中一個StorageClass指定為預設StorageClass。後面的命令範例顯示指定的 StorageClass 名稱 `ontap-ai-flexvols-retain` 為預設 StorageClass 。



NOTE: 「ontap-non-flexgroup」Trident後端類型的最小PVc尺寸相當大。根據預設、Kubeflow會嘗試配置大小只有幾GB的PVCS。因此、您不應將使用「ONTAP-NAAS-Flexgroup」後端類型的StorageClass指定為Kubefflow部署的預設StorageClass。

....
$ kubectl get sc
NAME                                PROVISIONER             AGE
ontap-ai-flexgroups-retain          csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1   csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2   csi.trident.netapp.io   25h
ontap-ai-flexvols-retain            csi.trident.netapp.io   3s
$ kubectl patch storageclass ontap-ai-flexvols-retain -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
storageclass.storage.k8s.io/ontap-ai-flexvols-retain patched
$ kubectl get sc
NAME                                 PROVISIONER             AGE
ontap-ai-flexgroups-retain           csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1    csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2    csi.trident.netapp.io   25h
ontap-ai-flexvols-retain (default)   csi.trident.netapp.io   54s
....


== Kubeflow 部署選項

部署 Kubeflow 有許多不同的選項。請參閱 link:https://www.kubeflow.org/docs/started/installing-kubeflow/["官方Kubeflow文件"] 如需部署選項清單、請選擇最適合您需求的選項。


NOTE: 為了驗證目的、我們使用部署 Kubeflow 1.7 link:https://www.deploykf.org["deploykF"] 0.1.1 。
