---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: 開放原始碼 MLOps 搭配 NetApp - 架構 
---
= 架構
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
此解決方案不取決於特定硬體。此解決方案與 NetApp Astra Trident 支援的任何 NetApp 實體儲存設備、軟體定義執行個體或雲端服務相容。範例包括 NetApp AFF 儲存系統、適用於 NetApp ONTAP 的 Amazon FSX 、 Azure NetApp Files 、 Google Cloud NetApp Volumes 或 NetApp Cloud Volumes ONTAP 執行個體。此外、只要 NetApp Astra Trident 和其他正在實作的解決方案元件支援使用的 Kubernetes 版本、即可在任何 Kubernetes 叢集上實作解決方案。如需 Trident 支援的 Kubernetes 版本清單，請參閱 https://docs.netapp.com/us-en/trident/index.html["Trident文件"^]。如需驗證此解決方案各種元件所用環境的詳細資訊、請參閱下表。



== Apache 氣流驗證環境

|===
| 軟體元件 | 版本 


| Apache Airflow | 2.2.1 、透過 8.0.8 部署 link:https://artifacthub.io/packages/helm/airflow-helm/airflow["Apache Airflow Helm 圖表"^] 


| Kubernetes | 1.18 


| NetApp Astra Trident | 21.01 
|===


== JupyterHub 驗證環境

|===
| 軟體元件 | 版本 


| JupyterHub | 4.1.5 、透過 3.3.7 部署 link:https://hub.jupyter.org/helm-chart/["JupyterHub Helm 圖表"^] 


| Kubernetes | 1.29 


| NetApp Astra Trident | 24.02 
|===


== MLflow 驗證環境

|===
| 軟體元件 | 版本 


| MLflow | 2.14.1 、透過 1.4.12 部署 link:https://artifacthub.io/packages/helm/bitnami/mlflow["MLflow Helm 圖表"^] 


| Kubernetes | 1.29 


| NetApp Astra Trident | 24.02 
|===


== Kubeflow 驗證環境

|===
| 軟體元件 | 版本 


| Kubeflow | 1.7 、透過 0.1.1 部署 link:https://www.deploykf.org["deploykF"^] 


| Kubernetes | 1.26 


| NetApp Astra Trident | 23.07 
|===


== 支援

NetApp 不支援 Apache Airflow 、 JupyterHub 、 MLflow 、 Kubefflow 或 Kubernetes 。如果您對完全支援的 MLOps 平台感興趣、 link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["請聯絡NetApp"^] 請參閱 NetApp 與合作夥伴共同提供的完全支援的 MLOps 解決方案。
