---
sidebar: sidebar 
permalink: ai/aipod_nv_conclusion_add_info.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, NVIDIA AI Enterprise, NVIDIA BasePOD, NVIDIA DGX 
summary: NetApp AIPod 搭配 NVIDIA DGX 系統 - 何處可以找到其他資訊 
---
= NetApp AIPod 搭配 NVIDIA DGX 系統 - 結論與其他資訊
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aipod_nv_validation_sizing.html["上一篇： NetApp AIPod 搭配 NVIDIA DGX 系統 - 解決方案驗證與規模調整指南"]



== 結論

DGX BasePOD 架構是新一代的深度學習平台、需要同樣進階的儲存與資料管理功能。透過將 DGX BasePOD 與 NetApp AFF 系統結合、 NetApp AIPod 架構幾乎可在任何規模上實作、從 OEM 伺服器中的單一 GPU 、搭配 AFF A250 儲存系統、在 24 節點 AFF A900 叢集上最多可達 48 個 DGX H100 系統。AFF 結合 NetApp ONTAP 優異的雲端整合功能和軟體定義功能、提供跨越邊緣、核心和雲端的完整資料傳輸管道、讓 DL 專案成功完成。



== 其他資訊

若要深入瞭解本文件所述資訊、請參閱下列文件和 / 或網站：

* NetApp ONTAP 數據管理軟體ONTAP —資訊庫
+
https://docs.netapp.com/us-en/ontap-family/["https://docs.netapp.com/us-en/ontap-family/"^]

* NetApp AFF A900 儲存系統 -
+
https://www.netapp.com/data-storage/aff-a-series/aff-a900/["https://www.netapp.com/data-storage/aff-a-series/aff-a900/"]

* NetApp ONTAP RDMA 資訊 -
+
link:https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html["https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html"]

* NetApp DataOps工具套件
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* NetApp Astra Trident
+
https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html["https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_overview_trident.html"^]

* ONTAP AI - 採用 NVIDIA DGX A100 系統的 NetApp 驗證架構
+
https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html["https://docs.netapp.com/us-en/netapp-solutions/ai/ontap-ai-overview.html"^]

* NVIDIA BasePOD
+
https://www.nvidia.com/en-us/data-center/dgx-basepod/["https://www.nvidia.com/en-us/data-center/dgx-basepod/"^]

* NVIDIA DGX A100 系統
+
https://www.nvidia.com/en-us/data-center/dgx-a100/["https://www.nvidia.com/en-us/data-center/dgx-a100/"^]

* NVIDIA Networking
+
https://www.nvidia.com/en-us/networking/["https://www.nvidia.com/en-us/networking/"^]

* NVIDIA AI Enterprise
+
https://www.nvidia.com/en-us/data-center/products/ai-enterprise/["https://www.nvidia.com/en-us/data-center/products/ai-enterprise/"^]





== 感謝

本文件為 NetApp 解決方案與 ONTAP 工程團隊的工作成果： David Arnette 、 Olga Kornievskaia 、 Dustin Fischer 、 Srikanth Kaligotla 、 Mohit Kumar 和 Rajeev Badrinath 。作者也想感謝 NVIDIA 和 BasePOD 工程團隊持續提供支援。
