---
sidebar: sidebar 
permalink: ai/aks-anf_click-through_rate_prediction_use_case_summary.html 
keywords: use case, terabyte click log, random forest, training 
summary: 本頁摘要說明Azure NetApp Files 分散式或大規模訓練的功能優勢。 
---
= 點選率預測使用案例摘要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_cloud_resource_requirements.html["先前：雲端資源需求。"]

[role="lead"]
此使用案例以公開提供的為基礎 http://labs.criteo.com/2013/12/download-terabyte-click-logs/["TB點選記錄"^] 資料集來源 https://ailab.criteo.com/["Criteo AI實驗室"^]。隨著ML平台與應用程式的最新進展、現在許多人都開始大規模學習。點閱率（CTR）定義為每百個線上廣告曝光點閱率（以百分比表示）的平均點閱率。在各種產業垂直市場和使用案例中、包括數位行銷、零售、電子商務和服務供應商、廣泛採用此技術作為主要指標。以下是使用CTR作為潛在客戶流量重要指標的範例：

* *數位行銷：* https://support.google.com/google-ads/answer/2615875?hl=en["Google Analytics"^]、CTR可用來衡量廣告商或商家的關鍵字、廣告及免費上市表現。高點閱率是使用者發現您的廣告和清單有用且相關的良好指標。此外、CTR也有助於達成關鍵字的預期CTR、這是的一項要素 https://support.google.com/google-ads/answer/1752122?hl=en["廣告排名"^]。
* *電子商務：*除了善用資源之外 https://analytics.google.com/analytics/web/provision/#/provision["Google Analytics"^]中、電子商務後端至少有一些訪客統計資料。雖然這些統計資料乍看之下似乎並不實用、但通常很容易閱讀、而且可能比其他資訊更準確。由這類統計資料組成的第一方資料集為專屬資料、因此與電子商務賣家、買家及平台最相關。這些資料集可用來設定基準、比較去年和昨天的結果、建立時間序列以供進一步分析。
* *零售：*零售商店可將訪客數量和客戶數量與CTR建立關聯。從銷售點記錄可以看出客戶的數量。零售商網站的點閱率或廣告流量可能導致上述銷售。忠誠度方案是另一個使用案例、因為客戶從線上廣告或其他網站重新導向、可能會加入以獲得獎勵。零售商可以透過忠誠度方案來贏得客戶、並記錄銷售記錄的行為、藉此建立一套建議系統、不僅能預測不同類別的消費者購買行為、也能將優惠券個人化、減少流失。
* *服務供應商：*電信公司和網際網路服務供應商擁有豐富的第一方使用者遙測資料、可提供深入見解的AI、ML和分析使用案例。舉例來說、電信公司可利用行動用戶的網路瀏覽、每日記錄最上層網域記錄、微調現有的模型、以製作最新的對象區隔、預測客戶行為、並與廣告商合作、以即時廣告方式提供更好的線上體驗。在這類資料導向的行銷工作流程中、CTR是反映轉換的重要指標。


就數位行銷而言、 http://labs.criteo.com/2013/12/download-terabyte-click-logs/["請按一下「Logs（記錄）」"^] 現在是評估ML平台與演算法擴充性的參考資料集。透過預測點擊率、廣告商可以選擇最有可能回應廣告的訪客、分析他們的瀏覽記錄、並根據使用者的興趣顯示最相關的廣告。

本技術報告所提供的解決方案強調下列優點：

* 分散式或大規模訓練的優勢Azure NetApp Files
* 支援CUDA的資料處理（cuDF、cuPy等）和ML演算法（cuML）
* 適用於分散式訓練的dask平行運算架構


端點對端點工作流程建立在「水流AI」和Azure NetApp Files 「速度AI」基礎上、顯示隨機樹系模式訓練時間大幅縮短兩個訂單。相較於傳統的「大作」方法、這項改善相當顯著、因為在處理實際的點擊記錄時、每天都會有45GB的結構化表格資料（平均）。這相當於包含約20億列的DataFrame。我們將示範叢集環境設定、架構與程式庫安裝、資料載入與處理、傳統與分散式訓練、視覺化與監控、並在本技術報告中比較關鍵的端點對端點執行時間結果。

link:aks-anf_install_and_set_up_the_aks_cluster.html["下一步：安裝並設定高效能叢集。"]
