---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= 使用案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
雖然目前所有的應用程式都不是AI驅動的、但這些應用程式仍在不斷演變、讓他們能夠存取AI的巨大效益。為了支援採用AI、應用程式需要一個基礎架構、為他們提供最佳運作所需的資源、並支援他們持續演進。

對於AI導向的應用程式、邊緣位置是主要的資料來源。在一段時間內從多個邊緣位置收集可用的資料、以構成訓練資料集時、可用於訓練。然後、訓練完成的模型便可部署回收集資料的邊緣位置、以便更快速地進行推斷、而不需要重複將正式作業資料傳輸到專用的推斷平台。

採用NetApp H615c運算節點、搭配NVIDIA T4 GPU和NetApp雲端連線儲存系統的NetApp H615c運算解決方案NetApp HCI 、由NetApp和NVIDIA開發驗證。此解決方案可解決模稜兩可的問題、消除設計的複雜性、並結束猜測、進而簡化邊緣資料中心的AI推斷解決方案部署。NetApp HCI此解決方案為IT組織提供規範性架構、可：

* 在邊緣資料中心啟用AI推斷
* 最佳化GPU資源的使用量
* 提供Kubernetes型推斷平台、以提供靈活度與擴充性
* 消除設計複雜性


邊緣資料中心可在離產生點非常近的位置管理及處理資料。這種接近性可提高效率、並減少處理資料所需的延遲時間。許多垂直市場已實現邊緣資料中心的效益、並正大力採用這種分散式資料處理方法。

下表列出邊緣垂直市場和應用程式。

|===
| 垂直 | 應用程式 


| 醫療 | 電腦輔助診斷可協助醫務人員偵測早期疾病 


| 石油與天然氣 | 自動檢查遠端正式作業設施、影片和影像分析 


| 航空 | 空中交通控制協助和即時視訊饋送分析 


| 媒體與娛樂 | 音訊/視訊內容篩選功能可提供適合家庭的內容 


| 商業分析 | 品牌知名度：在即時串流的電視活動中分析品牌外觀 


| 電子商務 | 聰明搭售供應商優惠、尋找理想的商家與倉儲組合 


| 零售 | 自動結帳功能可辨識客戶置於購物車中的項目、並促進數位付款 


| 智慧城市 | 改善交通流量、優化停車、並強化行人與自行車安全 


| 製造業 | 品質控制、組裝線路監控及瑕疵識別 


| 客戶服務 | 客戶服務自動化、可分析及分類查詢（電話、電子郵件及社群媒體） 


| 農業 | 智慧型農場營運與活動規劃、以最佳化施肥與除草劑應用 
|===


== 目標對象

解決方案的目標對象包括下列群組：

* 資料科學家
* IT架構設計師
* 現場顧問
* 專業服務
* IT經理
* 任何其他需要在邊緣位置提供IT創新及健全資料與應用程式服務的基礎架構的人

