---
sidebar: sidebar 
permalink: ai/vector-database-introduction.html 
keywords: vector database 
summary: NetApp 向量資料庫解決方案簡介 
---
= 簡介
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本節介紹 NetApp 的向量資料庫解決方案。



== 簡介

向量資料庫可有效因應大型語言模型（ LMS ）和泛用人工智慧（ AI ）中的語義搜尋複雜度所設計的挑戰。與傳統的資料管理系統不同、向量資料庫能夠處理及搜尋各種類型的資料、包括影像、影片、文字、音訊、 使用資料本身的內容、而非標籤或標籤、以及其他形式的非結構化資料。

Relational Database Management Systems （ RDBMS ）的侷限性已詳加記錄、尤其是在 AI 應用程式中、它們與高維度資料呈現和非結構化資料的爭用。RDBMS 通常需要耗時且容易出錯的程序、將資料整合至更容易管理的結構、導致搜尋延遲和效率不彰。然而、向量資料庫的設計旨在規避這些問題、提供更有效率且更準確的解決方案來管理及搜尋複雜的高維度資料、進而協助 AI 應用程式的發展。

本文件為目前使用或計畫使用向量資料庫的客戶提供全方位指南、詳述在 NetApp ONTAP 、 NetApp StorageGRID 、 Amazon FSxN for NetApp ONTAP 和 SnapCenter 等平台上使用向量資料庫的最佳實務做法。此處提供的內容涵蓋多個主題：

* NetApp 儲存設備透過 NetApp ONTAP 和 StorageGRID 物件儲存設備提供的向量資料庫基礎架構準則、例如 Milvus 。
* 透過檔案和物件存放區、驗證 AWS FSX for NetApp ONTAP 中的 Milvus 資料庫。
* 深入瞭解 NetApp 的檔案物件雙重性、展現其在向量資料庫及其他應用程式中的資料實用度。
* NetApp 的資料保護管理產品 SnapCenter 如何為向量資料庫資料提供備份與還原功能。
* NetApp 的混合雲如何在內部部署和雲端環境中提供資料複寫與保護。
* 深入瞭解 NetApp ONTAP 上的向量資料庫（例如 Milvus 和 pgvector ）的效能驗證。
* 兩種特定使用案例：擷取使用大語言模型（ LLM ）的擴增世代（ RAG ）、以及 NetApp IT 團隊的 ChatAI 、提供所概述概念和實務做法的實際範例。

