---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-considerations.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 這是 NetApp ONTAP 解決方案、用於設定、強化及驗證 ONTAP 型網路資料保險箱 
---
= 其他考量
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
設計和部署 ONTAP 型網路資料保險箱時、還有其他考量。



== 容量規模調整考量

ONTAP 網路資料保險箱目的地磁碟區所需的磁碟空間量取決於各種因素、其中最重要的因素是來源磁碟區資料的變更率。目的地磁碟區上的備份排程和 Snapshot 排程都會影響目的地磁碟區上的磁碟使用量、而且來源磁碟區上的變更率不太可能是固定的。建議您提供額外儲存容量的緩衝區、以滿足終端使用者或應用程式行為未來變更的需求。

在 ONTAP 中設定 1 個月的保留關係規模、需要根據多項因素來計算儲存需求、包括主要資料集的大小、資料變更率（每日變更率）、以及重複資料刪除和壓縮節省（如果適用）。

以下是逐步方法：

第一步是瞭解您使用網路資料保險箱保護的來源磁碟區大小。這是最初複寫至網路資料保險箱目的地的基本資料量。接下來、估計資料集的每日變更率。這是每天變更的資料百分比。瞭解資料動態的重要性。

例如：

* 主要資料集大小 = 5TB
* 每日變更率 = 5% （ 0.05 ）
* 重複資料刪除與壓縮效率 = 50% （ 0.50 ）


現在、讓我們逐一瞭解計算結果：

* 計算每日資料變更率：
+
`Changed data per day = 5000 * 5% = 250GB`

* 計算 30 天內變更的資料總計：
+
`Total changed data in 30 days = 250 GB * 14 = 3.5TB`

* 計算所需的總儲存容量：
+
`TOTAL = 5TB + 3.5TB = 8.5TB`

* 套用重複資料刪除與壓縮節省：
+
`EFFECTIVE = 8.5TB * 50% = 4.25TB`



* 儲存需求摘要 *

* 缺乏效率：需要 * 8.5TB* 來儲存 30 天的網路資料保險箱資料。
* 效率達 50% ：重複資料刪除和壓縮後需要使用 *4.25TB* 的儲存設備。



NOTE: 由於中繼資料、 Snapshot 複本可能會產生額外的負擔、但這通常是次要的。


NOTE: 如果每天執行多個備份、請根據每天執行的 Snapshot 複本數量來調整計算。


NOTE: 隨著時間的推移、資料成長的因素可確保規模調整符合未來需求。



== 效能對主要 / 來源的影響

由於資料傳輸是拉動作業、因此對主要儲存效能的影響可能會因工作負載、資料量和備份頻率而異。然而、整體效能對主要系統的影響通常中等且可管理、因為資料傳輸是為了將資料保護和備份工作卸載至網路資料保險箱儲存系統而設計。在初始關係設定和第一次完整備份期間、大量資料會從主要系統傳輸到網路資料保險箱系統（ SnapLock Compliance Volume ）。這可能會導致主要系統的網路流量增加和 I/O 負載增加。完成初始完整備份後、 ONTAP 只需追蹤和傳輸自上次備份以來變更的區塊。與初始複寫相比、這會造成更小的 I/O 負載。遞增更新效率極高、對主要儲存效能的影響也極微。資料保險箱程序會在背景執行、減少干擾主要系統正式作業工作負載的機會。

* 確保儲存系統擁有足夠的資源（ CPU 、記憶體和 IOP ）來處理額外的負載、可減輕效能影響。

