---
sidebar: sidebar 
permalink: automation/getting-started.html 
summary: NetApp解決方案自動化可讓客戶將許多常見的基礎架構和應用程式工作的部署、組態和執行自動化。 
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible, getting, started 
---
= NetApp解決方案自動化入門
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


[role="lead"]
NetApp解決方案自動化可為NetApp解決方案所使用的許多常見工作提供簡易性與重複性。

在執行任何解決方案自動化之前、必須針對自動化的執行方式設定環境。您可以選擇從命令列或透過AWX或直立式等工具來執行自動化作業。

下列各節將概述設定每個指定環境的環境所需步驟。

.在RHEL / CentOS上設定用於CLI部署的Ansible Control Node
====
. Ansible控制節點的需求：
+
.. 安裝下列套件的RHEL/CentOS機器：
+
... Python3.
... 管路3.
... Ansible（版本高於2.10.0）
... Git






如果您有一部全新的RHEL/CentOS機器、但未安裝上述需求、請依照下列步驟將該機器設定為「Ansible Control Node（可控制節點）」：

. 啟用RHEL-8/RHEL-7的Ansible儲存庫
+
.. 適用於RHEL-8（以root執行下列命令）
+
[source, cli]
----
subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
----
.. 適用於RHEL-7（以root執行下列命令）
+
[source, cli]
----
subscription-manager repos --enable rhel-7-server-ansible-2.9-rpms
----


. 建立.sh檔案
+
[source, cli]
----
vi setup.sh
----
. 將下列內容貼到檔案中
+
[source, cli]
----
#!/bin/bash
echo "Installing Python ------>"
sudo yum -y install python3 >/dev/null
echo "Installing Python Pip ------>"
sudo yum -y install python3-pip >/dev/null
echo "Installing Ansible ------>"
python3 -W ignore -m pip --disable-pip-version-check install ansible >/dev/null
echo "Installing git ------>"
sudo yum -y install git >/dev/null
----
. 將檔案設定為可執行檔
+
[source, cli]
----
chmod +x setup.sh
----
. 執行指令碼（以root使用者身份）
+
[source, cli]
----
./setup.sh
----


====
.設定Ansible Control Node、以便在Ubuntu / Debian上部署CLI
====
. Ansible控制節點的需求：
+
.. 安裝下列套件的Ubuntu / Debian機器：
+
... Python3.
... 管路3.
... Ansible（版本高於2.10.0）
... Git






如果您有新安裝的Ubuntu / Debian機器、但未安裝上述要求、請依照下列步驟將該機器設定為Ansible控制節點：

. 建立.sh檔案
+
[source, cli]
----
vi setup.sh
----
. 將下列內容貼到檔案中
+
[source, cli]
----
#!/bin/bash
echo "Installing Python ------>"
sudo apt-get -y install python3 >/dev/null
echo "Installing Python Pip ------>"
sudo apt-get -y install python3-pip >/dev/null
echo "Installing Ansible ------>"
python3 -W ignore -m pip --disable-pip-version-check install ansible >/dev/null
echo "Installing git ------>"
sudo apt-get -y install git >/dev/null
----
. 將檔案設定為可執行檔
+
[source, cli]
----
chmod +x setup.sh
----
. 執行指令碼（以root使用者身份）
+
[source, cli]
----
./setup.sh
----


====
.設定Ansible Tower或AWX進行直立式/ AWX部署
====
本節說明在AWX/Ansible Tower中設定參數所需的步驟、這些參數可讓環境做好使用NetApp自動化解決方案的準備。

. 設定庫存。
+
.. 瀏覽至「資源」→「庫存」→「新增」、然後按一下「新增庫存」。
.. 提供名稱和組織詳細資料、然後按一下「Save（儲存）」。
.. 在「Inventory（清單）」頁面中、按一下您剛建立的詳細目錄資源。
.. 如果有任何庫存變數、請將其貼到變數欄位。
.. 前往「Groups（群組）」子功能表、然後按一下「Add（新增）」
.. 提供群組名稱、複製群組變數（如有必要）、然後按一下「Save（儲存）」。
.. 按一下建立的群組、移至「hosts（主機）」子功能表、然後按一下「Add New Host（新增主機）」。
.. 提供主機的主機名稱和IP位址、貼上主機變數（如有必要）、然後按一下「Save（儲存）」。


. 建立認證類型。對於涉及ONTAP 到靜態、元素、VMware或任何其他HTTPS型傳輸連線的解決方案、您必須設定認證類型、使其符合使用者名稱和密碼項目。
+
.. 瀏覽至「管理」→「認證類型」、然後按一下「新增」。
.. 提供名稱和說明。
.. 將下列內容貼到輸入組態：




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. 將下列內容貼到Injector Configuration：


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. 設定認證資料。
+
.. 瀏覽至「資源」→「認證」、然後按一下「新增」
.. 輸入名稱和組織詳細資料。
.. 選取正確的認證類型；如果您想要使用標準SSH登入、請選取「機器」類型、或選取您建立的自訂認證類型。
.. 輸入其他對應的詳細資料、然後按一下「Save（儲存）」。


. 設定專案。
+
.. 瀏覽至「資源」→「專案」、然後按一下「新增」。
.. 輸入名稱和組織詳細資料。
.. 選取「來源控制認證類型」的Git。
.. 貼上與特定解決方案對應的來源控制URL（或git Clone URL）。
.. 或者、如果Git URL受到存取控制、請在來源控制認證中建立並附加對應的認證資料。
.. 按一下儲存。


. 設定工作範本。
+
.. 瀏覽至「資源」→「範本」→「新增」、然後按一下「新增工作範本」
.. 輸入名稱和說明。
.. 選取工作類型；執行會根據手冊來設定系統、檢查會執行播放手冊的乾式執行、而不會實際設定系統。
.. 選取該方針的對應庫存、專案和認證資料。
.. 選取您要作為工作範本一部分執行的方針。
.. 這些變數通常會在執行時期貼上。因此、若要在執行時間期間收到填入變數的提示、請務必勾選對應於變數欄位的啟動時核取方塊提示。
.. 視需要提供任何其他詳細資料、然後按一下「Save（儲存）」。


. 啟動工作範本。
+
.. 瀏覽至資源→範本。
.. 按一下所需的範本、然後按一下啟動。
.. 如果啟動時出現提示、請填寫任何變數、然後再按一下「Launch（重新啟動）」。




====